-- TenderHawk Supabase schema
-- Run this file in Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.company_profiles (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  company_name text not null default '', region text not null default '', trades text not null default '', capabilities text not null default '', references_text text not null default '',
  max_contract_value numeric not null default 0, capacity text not null default 'mittel' check (capacity in ('klein','mittel','gross')), match_threshold integer not null default 75 check (match_threshold between 0 and 100),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique (user_id)
);
create table if not exists public.saved_opportunities (
  id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, project_id text not null, publication_id text, title text not null, buyer text, location text, source_url text, score integer check (score between 0 and 100), decision text, notes text not null default '', saved_at timestamptz not null default now(), unique (user_id, project_id)
);
create table if not exists public.push_subscriptions (
  id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, endpoint text not null, p256dh text not null, auth_secret text not null, user_agent text, enabled boolean not null default true, threshold integer not null default 75 check (threshold between 0 and 100), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique (user_id, endpoint)
);

-- Anonymous first-party usage analytics. No names, email addresses or IP addresses are stored here.
create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_name text not null,
  session_id text not null,
  path text not null default '/',
  referrer text not null default 'direct',
  meta jsonb not null default '{}'::jsonb,
  user_agent text not null default '',
  created_at timestamptz not null default now()
);

create or replace function public.set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at = now(); return new; end; $$;
drop trigger if exists set_company_profiles_updated_at on public.company_profiles;
create trigger set_company_profiles_updated_at before update on public.company_profiles for each row execute function public.set_updated_at();
drop trigger if exists set_push_subscriptions_updated_at on public.push_subscriptions;
create trigger set_push_subscriptions_updated_at before update on public.push_subscriptions for each row execute function public.set_updated_at();

alter table public.company_profiles enable row level security;
alter table public.saved_opportunities enable row level security;
alter table public.push_subscriptions enable row level security;
alter table public.analytics_events enable row level security;

drop policy if exists "company_profiles_select_own" on public.company_profiles; create policy "company_profiles_select_own" on public.company_profiles for select to authenticated using (auth.uid() = user_id);
drop policy if exists "company_profiles_insert_own" on public.company_profiles; create policy "company_profiles_insert_own" on public.company_profiles for insert to authenticated with check (auth.uid() = user_id);
drop policy if exists "company_profiles_update_own" on public.company_profiles; create policy "company_profiles_update_own" on public.company_profiles for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "company_profiles_delete_own" on public.company_profiles; create policy "company_profiles_delete_own" on public.company_profiles for delete to authenticated using (auth.uid() = user_id);
drop policy if exists "saved_opportunities_select_own" on public.saved_opportunities; create policy "saved_opportunities_select_own" on public.saved_opportunities for select to authenticated using (auth.uid() = user_id);
drop policy if exists "saved_opportunities_insert_own" on public.saved_opportunities; create policy "saved_opportunities_insert_own" on public.saved_opportunities for insert to authenticated with check (auth.uid() = user_id);
drop policy if exists "saved_opportunities_update_own" on public.saved_opportunities; create policy "saved_opportunities_update_own" on public.saved_opportunities for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "saved_opportunities_delete_own" on public.saved_opportunities; create policy "saved_opportunities_delete_own" on public.saved_opportunities for delete to authenticated using (auth.uid() = user_id);
drop policy if exists "push_subscriptions_select_own" on public.push_subscriptions; create policy "push_subscriptions_select_own" on public.push_subscriptions for select to authenticated using (auth.uid() = user_id);
drop policy if exists "push_subscriptions_insert_own" on public.push_subscriptions; create policy "push_subscriptions_insert_own" on public.push_subscriptions for insert to authenticated with check (auth.uid() = user_id);
drop policy if exists "push_subscriptions_update_own" on public.push_subscriptions; create policy "push_subscriptions_update_own" on public.push_subscriptions for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "push_subscriptions_delete_own" on public.push_subscriptions; create policy "push_subscriptions_delete_own" on public.push_subscriptions for delete to authenticated using (auth.uid() = user_id);
-- Visitors may append anonymous events, but cannot read the analytics table from the browser.
drop policy if exists "analytics_insert_anon" on public.analytics_events; create policy "analytics_insert_anon" on public.analytics_events for insert to anon with check (true);
drop policy if exists "analytics_insert_authenticated" on public.analytics_events; create policy "analytics_insert_authenticated" on public.analytics_events for insert to authenticated with check (true);

create index if not exists company_profiles_user_id_idx on public.company_profiles(user_id);
create index if not exists saved_opportunities_user_id_idx on public.saved_opportunities(user_id);
create index if not exists saved_opportunities_project_id_idx on public.saved_opportunities(project_id);
create index if not exists push_subscriptions_user_id_idx on public.push_subscriptions(user_id);
create index if not exists analytics_events_created_at_idx on public.analytics_events(created_at desc);
create index if not exists analytics_events_event_name_idx on public.analytics_events(event_name);
