/* RESERVE Autopilot v2.5 — household foresight and three-choice cook decision. */
(function(){
 const DAY=86400000,NORM=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/g,'');
 const pantry=()=>window.RESERVE_PANTRY_INTELLIGENCE,confidenceOk=x=>x?.learned&&(x.learned.confidence==='medium'||x.learned.confidence==='high');
 const esc=s=>String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;'),qty=(v,u)=>`${Math.round(v*10)/10} ${u}`;
 const recipes=()=>{try{if(Array.isArray(window.recipes))return window.recipes}catch{}return[]},ingredientMatch=(a,b)=>{a=NORM(a);b=NORM(b);return !!a&&!!b&&(a===b||a.includes(b)||b.includes(a))};
 const minutes=r=>Number(r.totalTime||r.time||r.minutes||((Number(r.prepTime)||0)+(Number(r.cookTime)||0)))||999;
 function horizon(days=30){const api=pantry();if(!api?.quantityForecast)return{days,ready:false,items:[],actions:[]};const items=api.quantityForecast(days).map(x=>{const coverage=Number.isFinite(x.normalCoverageDays)?Math.max(0,x.normalCoverageDays):null,runout=coverage===null?null:new Date(Date.now()+coverage*DAY).toISOString().slice(0,10),expiryRisk=x.nearestNormalExpiry<9999&&coverage!==null&&x.nearestNormalExpiry<coverage,reliable=confidenceOk(x);let buyInDays=null,buyAmount=0;if(reliable&&x.dailyUse>0){buyInDays=Math.max(0,Math.floor((x.normal/x.dailyUse)-3));buyAmount=Math.max(0,(x.dailyUse*days)-x.normal)}return{...x,coverageDays:coverage,runout,expiryRisk,reliable,buyInDays,buyAmount}});const actions=[];for(const x of items){if(x.expiryRisk)actions.push({type:'use-first',priority:100,name:x.name,days:x.nearestNormalExpiry});if(x.reliable&&x.buyAmount>0)actions.push({type:'buy',priority:x.buyInDays<=7?90:70,name:x.name,amount:x.buyAmount,unit:x.unit,buyInDays:x.buyInDays,confidence:x.learned.confidence});if(x.reserveWouldBeNeeded)actions.push({type:'protect-reserve',priority:95,name:x.name})}actions.sort((a,b)=>b.priority-a.priority);return{days,ready:true,items,actions}}
 function shoppingCandidates(days=30){return horizon(days).actions.filter(x=>x.type==='buy'&&x.buyInDays<=7&&(x.confidence==='medium'||x.confidence==='high'))}
 function shoppingWindows(days=30){const c=shoppingCandidates(days),defs=[{id:'now',label:'Jetzt / nächste 2 Tage',min:0,max:2},{id:'soon',label:'In 3–5 Tagen',min:3,max:5},{id:'week',label:'In 6–7 Tagen',min:6,max:7}];return defs.map(w=>({...w,items:c.filter(x=>x.buyInDays>=w.min&&x.buyInDays<=w.max)})).filter(w=>w.items.length)}
 function rescuePlan(days=7){const risks=horizon(30).actions.filter(x=>x.type==='use-first'&&x.days<=days),rs=recipes();if(!risks.length||!rs.length)return[];return rs.map(recipe=>{const saved=risks.filter(r=>(recipe.ingredients||[]).some(i=>ingredientMatch(i.name,r.name)));if(!saved.length)return null;let fit=0;try{fit=Number(window.RESERVE_AUTOPILOT?.fitRatio?.(recipe)||0)}catch{}const urgency=saved.reduce((s,r)=>s+Math.max(1,8-Math.max(0,r.days)),0),score=saved.length*160+urgency*12+fit*150-Math.max(0,1-fit)*100;return{recipe,saved,fit,score}}).filter(Boolean).sort((a,b)=>b.score-a.score).slice(0,5)}
 function cookChoices(){const rs=recipes();if(!rs.length)return[];const rescue=rescuePlan(7),rescueById=new Map(rescue.map(x=>[x.recipe.id,x]));const scored=rs.map(recipe=>{let fit=0;try{fit=Number(window.RESERVE_AUTOPILOT?.fitRatio?.(recipe)||0)}catch{}const rr=rescueById.get(recipe.id),saved=rr?.saved||[],time=minutes(recipe),bestScore=fit*220+saved.length*100+(time<999?Math.max(0,60-time):0);return{recipe,fit,saved,time,bestScore}}).filter(x=>x.fit>0||x.saved.length);if(!scored.length)return[];const used=new Set(),pick=(label,reason,arr)=>{const x=arr.find(v=>!used.has(v.recipe.id));if(!x)return null;used.add(x.recipe.id);return{label,reason,...x}};const out=[];const best=pick('Beste Wahl','stärkste Kombination aus Vorrat, Zeit und Lebensmittelrettung',[...scored].sort((a,b)=>b.bestScore-a.bestScore));if(best)out.push(best);const fast=pick('Schnellste Wahl','kürzeste passende Zubereitungszeit',[...scored].filter(x=>x.time<999).sort((a,b)=>a.time-b.time||b.fit-a.fit));if(fast)out.push(fast);const save=pick('Rettet am meisten','verbraucht möglichst viele gefährdete Lebensmittel',[...scored].filter(x=>x.saved.length).sort((a,b)=>b.saved.length-a.saved.length||b.fit-a.fit));if(save)out.push(save);return out}
 window.autopilotV2Rescue=id=>{try{if(typeof startCook==='function'){startCook(id);return}}catch{}try{if(typeof showPanel==='function')showPanel('search')}catch{}};
 function addShoppingSuggestions(days=30,id=null){const windows=shoppingWindows(days),chosen=id?windows.find(w=>w.id===id):null,candidates=chosen?chosen.items:shoppingCandidates(days);if(!candidates.length)return 0;let list;try{list=typeof shopping!=='undefined'&&Array.isArray(shopping)?shopping:window.shopping}catch{return 0}if(!Array.isArray(list))return 0;for(const c of candidates){const existing=list.find(x=>x.autopilotV2Generated&&NORM(x.n)===NORM(c.name)&&!x.emergencyGenerated&&!x.reserveRotationGenerated),label=windows.find(w=>w.items.includes(c))?.label||'30-Tage-Prognose',meta={n:c.name,q:qty(c.amount,c.unit),autopilotGenerated:true,autopilotV2Generated:true,shoppingWindow:label,shoppingReasons:[`${label} · ${c.confidence==='high'?'hohe':'mittlere'} Datensicherheit`]};if(existing)Object.assign(existing,meta);else list.push(meta)}try{if(typeof saveShop==='function')saveShop();else localStorage.setItem('reserveShopping',JSON.stringify(list))}catch{}return candidates.length}
 window.autopilotV2AddShopping=id=>addShoppingSuggestions(30,id);
 function render(){const host=document.getElementById('home')||document.querySelector('main');if(!host)return;document.getElementById('autopilotV2')?.remove();const choices=cookChoices(),windows=shoppingWindows(30),box=document.createElement('div');box.id='autopilotV2';box.className='card';box.innerHTML=`<h2>Was soll ich heute kochen?</h2><p class="muted">Drei klare Entscheidungen statt einer langen Rezeptliste.</p>${choices.map(c=>`<div class="item" style="margin-top:8px"><b>${esc(c.label)} · ${esc(c.recipe.name)}</b><div class="small muted">${esc(c.reason)}${c.time<999?` · ${c.time} Min.`:''}${c.saved.length?` · rettet ${c.saved.map(x=>esc(x.name)).join(', ')}`:''}</div><button onclick="autopilotV2Rescue('${esc(c.recipe.id)}')">Dieses Gericht kochen</button></div>`).join('')||'<div class="small muted">Noch nicht genug Vorratsdaten für eine belastbare Entscheidung.</div>'}<h3 style="margin-top:14px">30-Tage-Ausblick</h3>${windows.map(w=>`<div class="item"><b>${esc(w.label)}</b><div class="small muted">${w.items.map(x=>esc(x.name)).join(' · ')}</div><button onclick="autopilotV2AddShopping('${w.id}')">Einkaufsfenster übernehmen</button></div>`).join('')||'<div class="small muted">Aktuell keine belastbaren Nachkäufe in den nächsten 7 Tagen.</div>'}`;host.prepend(box)}
 window.RESERVE_AUTOPILOT_V2={version:'2.5',horizon,shoppingCandidates,shoppingWindows,rescuePlan,cookChoices,addShoppingSuggestions,render};
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',render);else render();
})();