/* RESERVE Autopilot v3: strict meal slots, partial stock reservation, stronger variety. */
(function(){
  const DAY=86400000, SLOTS=[['Frühstück','Frühstück'],['Mittagessen','Mittagessen'],['Abendessen','Abendessen']];
  const unitOf=i=>(i.unit||'').toLowerCase()==='stück'?'stück':(i.unit||'').toLowerCase();
  const expDays=s=>{if(!s||!s.e)return 9999;return Math.ceil((new Date(s.e+'T23:59:59').getTime()-Date.now())/DAY)};
  const matches=(a,b)=>{a=N(a);b=N(b);return a===b||a.includes(b)||b.includes(a)};
  function approved(){return recipes.filter(r=>(!r.status||r.status==='approved')&&allowed(r))}
  function forSlot(r,slot){const mt=r.mealTimes||[];if(mt.length)return mt.includes(slot);return slot==='Frühstück'?r.type==='Frühstück':r.type==='Hauptmahlzeit'}
  function urgency(r){return adaptRecipe(r).ingredients.reduce((score,i)=>{let d=stock.filter(s=>matches(s.n,i.name)).map(expDays).sort((a,b)=>a-b)[0];return score+(d<=1?15:d<=3?10:d<=7?5:0)},0)}
  function ledgerAvailable(ledger,name,unit){let e=ledgerEntry(ledger,name);return e&&String(e.u).toLowerCase()===unit?e.v:0}
  function missingUnits(r,ledger){return adaptRecipe(r).ingredients.reduce((n,i)=>n+(ledgerAvailable(ledger,i.name,unitOf(i))>=i.amount*persons()?0:1),0)}
  function fitRatio(r,ledger){let a=adaptRecipe(r).ingredients,total=0,covered=0;a.forEach(i=>{let need=i.amount*persons();total+=need;covered+=Math.min(need,ledgerAvailable(ledger,i.name,unitOf(i)))});return total?covered/total:0}
  function nutritionScore(r){let n=r.nutrition||{},p=profile();if(p.goal==='Proteinreich')return +(n.protein||0);if(p.goal==='Ballaststoffreich')return +(n.fiber||0)*2;if(p.goal==='Kalorienärmer')return -(+(n.kcal||0));return 0}
  function choose(slot,ledger,counts,lastIds){let candidates=approved().filter(r=>forSlot(r,slot));return candidates.map(r=>({r,fit:recipeFitsLedger(r,ledger),ratio:fitRatio(r,ledger),urgent:urgency(r),missing:missingUnits(r,ledger),repeat:counts[r.id]||0,recent:lastIds.includes(r.id)?1:0,nutrition:nutritionScore(r),minutes:(r.prepMinutes||0)+(r.cookMinutes||0)})).sort((a,b)=>(a.recent-b.recent)||(a.repeat-b.repeat)||(b.fit-a.fit)||(b.ratio-a.ratio)||(b.urgent-a.urgent)||(a.missing-b.missing)||(b.nutrition-a.nutrition)||(a.minutes-b.minutes))[0]?.r||null}
  function reservePartial(base,ledger){let r=adaptRecipe(base);r.ingredients.forEach(i=>{let u=unitOf(i),need=i.amount*persons(),e=ledgerEntry(ledger,i.name);if(!e||String(e.u).toLowerCase()!==u)return;e.v=Math.max(0,e.v-Math.min(e.v,need))})}
  function plan(days=7){let ledger=stockLedger(),counts={},daysOut=[],lastIds=[];for(let d=0;d<days;d++){let meals=[];for(const [key,label] of SLOTS){let r=choose(key,ledger,counts,lastIds);meals.push({slot:label,recipe:r});if(r){counts[r.id]=(counts[r.id]||0)+1;reservePartial(r,ledger);lastIds.push(r.id);if(lastIds.length>6)lastIds.shift()}}daysOut.push(meals)}return {days:daysOut,ledger}}
  function flatten(p){return p.days.flat().map(x=>x.recipe).filter(Boolean)}
  function shoppingFor(items){let ledger=stockLedger(),map={};items.forEach(base=>{let r=adaptRecipe(base);r.ingredients.forEach(i=>{let u=unitOf(i),need=i.amount*persons(),e=ledgerEntry(ledger,i.name),have=e&&String(e.u).toLowerCase()===u?e.v:0,take=Math.min(have,need);if(e)e.v-=take;let miss=need-take;if(miss>0){let k=N(i.name)+'|'+u;if(!map[k])map[k]={name:i.name,amount:0,unit:i.unit};map[k].amount+=miss}})});return Object.values(map)}
  function addShopping(items){let additions=shoppingFor(items);additions.forEach(x=>shopping.push({n:x.name,q:fmt(x.amount,unitOf(x))}));if(additions.length&&typeof saveShop==='function')saveShop();return additions.length}
  function expiring(){return stock.filter(s=>expDays(s)<=3).sort((a,b)=>expDays(a)-expDays(b))}
  function render(){let host=document.getElementById('mealPlan');if(!host)return;document.getElementById('reserveAutopilot')?.remove();let p=plan(7),items=flatten(p),missing=shoppingFor(items),soon=expiring();let card=document.createElement('div');card.id='reserveAutopilot';card.className='card';card.innerHTML=`<h2>RESERVE Autopilot</h2><p class="muted">7 Tage mit Frühstück, Mittag- und Abendessen. Vorrat, MHD, Abwechslung und Profilziele werden berücksichtigt.</p><div class="small"><strong>${items.length}/21</strong> Mahlzeiten geplant · <strong>${soon.length}</strong> bald fällige Vorräte · <strong>${missing.length}</strong> Einkaufspositionen</div><div style="margin-top:10px">${p.days.map((meals,i)=>`<div style="padding:8px 0;border-bottom:1px solid rgba(255,255,255,.08)"><strong>Tag ${i+1}</strong>${meals.map(m=>`<div class="small">${m.slot}: ${m.recipe?m.recipe.name:'Noch kein passendes Rezept'}</div>`).join('')}</div>`).join('')}</div><button id="reserveAutoShop" ${missing.length?'':'disabled'}>Fehlende Mengen zur Einkaufsliste</button>`;host.prepend(card);let b=document.getElementById('reserveAutoShop');if(b)b.onclick=()=>{let n=addShopping(items);b.textContent=n?`${n} Positionen ergänzt`:'Einkauf bereits vollständig';b.disabled=true}}
  window.RESERVE_AUTOPILOT={plan,shoppingFor,expiring,flatten,recipeCount:()=>recipes.length,render,forSlot};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',render);else render();
})();
