/* RESERVE Autopilot v6.1: waste-aware planning with strategic emergency-reserve protection. */
(function(){
 const DAY=86400000,SLOTS=[['Frühstück','Frühstück'],['Mittagessen','Mittagessen'],['Abendessen','Abendessen']];
 const unitOf=i=>(i.unit||'').toLowerCase()==='stück'?'stück':(i.unit||'').toLowerCase();
 const expDays=s=>{if(!s||!s.e)return 9999;return Math.ceil((new Date(s.e+'T23:59:59').getTime()-Date.now())/DAY)};
 const matches=(a,b)=>{a=N(a);b=N(b);return a===b||a.includes(b)||b.includes(a)},pref=()=>typeof profile==='function'?(profile()||{}):{};
 function emergency(){try{return window.RESERVE_EMERGENCY?.protectedReserve?.()||null}catch{return null}}
 function approved(){return recipes.filter(r=>(!r.status||r.status==='approved')&&allowed(r))}
 function forSlot(r,slot){const mt=r.mealTimes||[];if(mt.length)return mt.includes(slot);return slot==='Frühstück'?r.type==='Frühstück':r.type==='Hauptmahlzeit'}
 function batchesFor(name,unit){return stock.filter(s=>matches(s.n,name)&&String(s.u||'').toLowerCase()===unit).slice().sort((a,b)=>expDays(a)-expDays(b))}
 function urgency(r){return adaptRecipe(r).ingredients.reduce((score,i)=>{const b=batchesFor(i.name,unitOf(i));if(!b.length)return score;const d=expDays(b[0]);return score+(d<=0?24:d<=1?18:d<=3?12:d<=7?6:0)},0)}
 function expiryUseScore(r){return adaptRecipe(r).ingredients.reduce((score,i)=>{const need=i.amount*persons(),b=batchesFor(i.name,unitOf(i));let left=need;for(const s of b){if(left<=0)break;const q=+(s.q||0),take=Math.min(left,q),d=expDays(s);score+=take/Math.max(need,1)*(d<=0?30:d<=1?22:d<=3?14:d<=7?7:1);left-=take}return score},0)}
 function ledgerAvailable(ledger,name,unit){ledger=ledger||stockLedger();let e=ledgerEntry(ledger,name);return e&&String(e.u).toLowerCase()===unit?e.v:0}
 function missingUnits(r,ledger){ledger=ledger||stockLedger();return adaptRecipe(r).ingredients.reduce((n,i)=>n+(ledgerAvailable(ledger,i.name,unitOf(i))>=i.amount*persons()?0:1),0)}
 function missingAmountRatio(r,ledger){ledger=ledger||stockLedger();const a=adaptRecipe(r).ingredients;if(!a.length)return 1;return a.reduce((sum,i)=>{const need=i.amount*persons(),have=ledgerAvailable(ledger,i.name,unitOf(i));return sum+(need?Math.max(0,need-have)/need:0)},0)/a.length}
 function fitRatio(r,ledger){return 1-missingAmountRatio(r,ledger)}
 function resilienceScore(r){const x=r.resilience;if(!x)return 0;const p=pref(),mode=p.resilienceMode||p.emergencyMode||'';let s=0;if(x.noCook)s+=mode==='noCook'?12:1;if(x.power==='none')s+=mode==='blackout'?12:1;else if(x.power==='low')s+=mode==='blackout'?5:.5;if(x.refrigeration==='none')s+=mode==='blackout'?6:.5;if(x.onePot)s+=1;s+=(+(x.shelfStableShare||0))*2;return s}
 function reserveRisk(r){const e=emergency();if(!e?.enabled)return 0;const x=r.resilience;if(!x)return 0;let risk=0;if(e.mealGap>0&&(x.noCook||x.power==='none'||x.refrigeration==='none'))risk+=18*(+(x.shelfStableShare||.25));if(e.mealGap===0&&e.mealTarget>0&&(x.noCook||x.power==='none'))risk+=10*(+(x.shelfStableShare||.25));return risk}
 function nutritionScore(r){let n=r.nutrition||{},p=pref();if(p.goal==='Proteinreich')return +(n.protein||0);if(p.goal==='Ballaststoffreich')return +(n.fiber||0)*2;if(p.goal==='Kalorienärmer')return -(+(n.kcal||0));return 0}
 function dayNutritionScore(r,day){let n=r.nutrition||{},k=+(n.kcal||0),protein=+(n.protein||0),fiber=+(n.fiber||0),after={kcal:day.kcal+k,protein:day.protein+protein,fiber:day.fiber+fiber},score=0;if(after.kcal>2400)score-=(after.kcal-2400)/25;if(after.protein<90)score+=protein*.35;if(after.fiber<30)score+=fiber*.7;return score}
 function timeAllowed(r){const p=pref(),max=+(p.maxMinutes||p.maxTime||0),minutes=(r.prepMinutes||0)+(r.cookMinutes||0);return !max||minutes<=max}
 function reasonFor(r,ledger,day){let ratio=fitRatio(r,ledger),u=urgency(r),n=r.nutrition||{},p=pref(),risk=reserveRisk(r);if(risk>4)return 'schont nach Möglichkeit deine strategische Reserve';if(u>=18)return 'rettet sehr bald ablaufenden Vorrat';if(u>=6)return 'verbraucht bald fälligen Vorrat';if(ratio>=.999)return 'vollständig aus deinem Vorrat';if(ratio>=.75)return 'benötigt nur wenig zusätzlichen Einkauf';if(p.resilienceMode==='blackout'&&r.resilience?.power==='none')return 'funktioniert auch ohne Strom';if(p.goal==='Proteinreich'&&+(n.protein||0)>=25)return 'passt zu deinem Proteinziel';if(p.goal==='Ballaststoffreich'&&+(n.fiber||0)>=7)return 'ballaststoffreiche Wahl';if(p.goal==='Kalorienärmer'&&+(n.kcal||0)<=500)return 'kalorienärmere Wahl';if(day.protein<60&&+(n.protein||0)>=20)return 'verbessert die Tages-Proteinbalance';return 'sorgt für Abwechslung im Wochenplan'}
 function choose(slot,ledger,counts,lastIds,day){let candidates=approved().filter(r=>forSlot(r,slot)&&timeAllowed(r));if(!candidates.length)candidates=approved().filter(r=>forSlot(r,slot));return candidates.map(r=>{const fit=recipeFitsLedger(r,ledger),ratio=fitRatio(r,ledger),missing=missingUnits(r,ledger),missingRatio=missingAmountRatio(r,ledger),urgent=urgency(r),expiry=expiryUseScore(r),repeat=counts[r.id]||0,recent=lastIds.includes(r.id)?1:0,nutrition=nutritionScore(r),dayNutrition=dayNutritionScore(r,day),resilience=resilienceScore(r),risk=reserveRisk(r),minutes=(r.prepMinutes||0)+(r.cookMinutes||0);const score=(fit?120:0)+ratio*55+expiry*2.2+urgent*1.4-missing*13-missingRatio*25-repeat*20-recent*32+dayNutrition+nutrition*.25+resilience-risk-minutes*.04;return {r,score}}).sort((a,b)=>b.score-a.score)[0]?.r||null}
 function reservePartial(base,ledger){let r=adaptRecipe(base);r.ingredients.forEach(i=>{let u=unitOf(i),need=i.amount*persons(),e=ledgerEntry(ledger,i.name);if(!e||String(e.u).toLowerCase()!==u)return;e.v=Math.max(0,e.v-Math.min(e.v,need))})}
 function addNutrition(day,r){let n=r?.nutrition||{};day.kcal+=+(n.kcal||0);day.protein+=+(n.protein||0);day.fiber+=+(n.fiber||0)}
 function plan(days=7){let ledger=stockLedger(),counts={},daysOut=[],lastIds=[];for(let d=0;d<days;d++){let meals=[],day={kcal:0,protein:0,fiber:0};for(const [key,label] of SLOTS){let r=choose(key,ledger,counts,lastIds,day),reason=r?reasonFor(r,ledger,day):'';meals.push({slot:label,recipe:r,reason});if(r){counts[r.id]=(counts[r.id]||0)+1;reservePartial(r,ledger);addNutrition(day,r);lastIds.push(r.id);if(lastIds.length>6)lastIds.shift()}}meals.nutrition=day;daysOut.push(meals)}return {days:daysOut,ledger}}
 function flatten(p){return p.days.flat().map(x=>x.recipe).filter(Boolean)}
 function shoppingFor(items){let ledger=stockLedger(),map={};items.forEach(base=>{let r=adaptRecipe(base);r.ingredients.forEach(i=>{let u=unitOf(i),need=i.amount*persons(),e=ledgerEntry(ledger,i.name),have=e&&String(e.u).toLowerCase()===u?e.v:0,take=Math.min(have,need);if(e)e.v-=take;let miss=need-take;if(miss>0){let k=N(i.name)+'|'+u;if(!map[k])map[k]={name:i.name,amount:0,unit:i.unit};map[k].amount+=miss}})});return Object.values(map)}
 function addShopping(items){let additions=shoppingFor(items);additions.forEach(x=>shopping.push({n:x.name,q:fmt(x.amount,unitOf(x)),autopilotGenerated:true}));if(additions.length&&typeof saveShop==='function')saveShop();return additions.length}
 function expiring(){return stock.filter(s=>expDays(s)<=3).sort((a,b)=>expDays(a)-expDays(b))}
 function render(){let host=document.getElementById('mealPlan');if(!host)return;document.getElementById('reserveAutopilot')?.remove();let p=plan(7),items=flatten(p),missing=shoppingFor(items),soon=expiring(),e=emergency();let reserveText=e?.enabled?` · Reserve ${e.safe?'im Ziel':'unter Ziel'}`:'';let card=document.createElement('div');card.id='reserveAutopilot';card.className='card';card.innerHTML=`<h2>RESERVE Autopilot</h2><p class="muted">7 Tage automatisch optimiert: MHD, Vorrat, Einkauf, Abwechslung und geschützte Notreserve werden gemeinsam bewertet.</p><div class="small"><strong>${items.length}/21</strong> Mahlzeiten geplant · <strong>${soon.length}</strong> in ≤3 Tagen fällig · <strong>${missing.length}</strong> Einkaufspositionen${reserveText}</div><div style="margin-top:10px">${p.days.map((meals,i)=>`<div style="padding:8px 0;border-bottom:1px solid rgba(255,255,255,.08)"><strong>Tag ${i+1}</strong><span class="small"> · ${Math.round(meals.nutrition.kcal)} kcal · ${Math.round(meals.nutrition.protein)} g Protein · ${Math.round(meals.nutrition.fiber)} g Ballaststoffe</span>${meals.map(m=>`<div class="small">${m.slot}: ${m.recipe?m.recipe.name:'Noch kein passendes Rezept'}${m.reason?` <span title="Warum dieses Rezept?">· ${m.reason}</span>`:''}</div>`).join('')}</div>`).join('')}</div><button id="reserveAutoShop" ${missing.length?'':'disabled'}>Fehlende Mengen zur Einkaufsliste</button>`;host.prepend(card);let b=document.getElementById('reserveAutoShop');if(b)b.onclick=()=>{let n=addShopping(items);b.textContent=n?`${n} Positionen ergänzt`:'Einkauf bereits vollständig';b.disabled=true}}
 window.RESERVE_AUTOPILOT={version:'6.1',plan,shoppingFor,expiring,flatten,recipeCount:()=>recipes.length,render,forSlot,fitRatio,missingAmountRatio,expiryUseScore,resilienceScore,reserveRisk};
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',render);else render();
})();
