/* RESERVE Autopilot v2.3 — 30-day foresight, shopping windows and expiry rescue recipes. */
(function(){
 const DAY=86400000,NORM=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/g,'');
 const pantry=()=>window.RESERVE_PANTRY_INTELLIGENCE;
 const confidenceOk=x=>x?.learned&&(x.learned.confidence==='medium'||x.learned.confidence==='high');
 const esc=s=>String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
 const qty=(v,u)=>{try{return typeof fmt==='function'?fmt(v,u):`${Math.round(v*10)/10} ${u}`}catch{return `${Math.round(v*10)/10} ${u}`}};
 const recipes=()=>{try{if(typeof window.recipes!=='undefined'&&Array.isArray(window.recipes))return window.recipes}catch{}try{if(typeof globalThis.recipes!=='undefined'&&Array.isArray(globalThis.recipes))return globalThis.recipes}catch{}return[]};
 const ingredientMatch=(a,b)=>{a=NORM(a);b=NORM(b);return !!a&&!!b&&(a===b||a.includes(b)||b.includes(a))};
 function horizon(days=30){const api=pantry();if(!api?.quantityForecast)return{days,ready:false,items:[],actions:[]};const items=api.quantityForecast(days).map(x=>{const coverage=Number.isFinite(x.normalCoverageDays)?Math.max(0,x.normalCoverageDays):null,runout=coverage===null?null:new Date(Date.now()+coverage*DAY).toISOString().slice(0,10),expiryRisk=x.nearestNormalExpiry<9999&&coverage!==null&&x.nearestNormalExpiry<coverage,reliable=confidenceOk(x);let buyInDays=null,buyAmount=0;if(reliable&&x.dailyUse>0){buyInDays=Math.max(0,Math.floor((x.normal/x.dailyUse)-3));buyAmount=Math.max(0,(x.dailyUse*days)-x.normal)}return{...x,coverageDays:coverage,runout,expiryRisk,reliable,buyInDays,buyAmount}});const actions=[];for(const x of items){if(x.expiryRisk)actions.push({type:'use-first',priority:100,name:x.name,days:x.nearestNormalExpiry,text:`${x.name} voraussichtlich vor Verbrauchsende aufbrauchen.`});if(x.reliable&&x.buyAmount>0)actions.push({type:'buy',priority:x.buyInDays<=7?90:70,name:x.name,amount:x.buyAmount,unit:x.unit,buyInDays:x.buyInDays,confidence:x.learned.confidence,text:`${x.name}: Nachkauf in ca. ${x.buyInDays} Tagen einplanen.`});if(x.reserveWouldBeNeeded)actions.push({type:'protect-reserve',priority:95,name:x.name,text:`${x.name}: Normalbestand reicht nicht; strategische Reserve bleibt geschützt.`})}actions.sort((a,b)=>b.priority-a.priority);return{days,ready:true,items,actions}}
 function shoppingCandidates(days=30){return horizon(days).actions.filter(x=>x.type==='buy'&&x.buyInDays<=7&&(x.confidence==='medium'||x.confidence==='high'))}
 function shoppingWindows(days=30){const c=shoppingCandidates(days),defs=[{id:'now',label:'Jetzt / nächste 2 Tage',min:0,max:2},{id:'soon',label:'In 3–5 Tagen',min:3,max:5},{id:'week',label:'In 6–7 Tagen',min:6,max:7}];return defs.map(w=>({...w,items:c.filter(x=>x.buyInDays>=w.min&&x.buyInDays<=w.max)})).filter(w=>w.items.length)}
 function rescueCandidates(days=7){const risks=horizon(30).actions.filter(x=>x.type==='use-first'&&x.days<=days),rs=recipes();return risks.map(risk=>{const matches=rs.map(recipe=>{const hits=(recipe.ingredients||[]).filter(i=>ingredientMatch(i.name,risk.name)).length;if(!hits)return null;let fit=0;try{fit=Number(window.RESERVE_AUTOPILOT?.fitRatio?.(recipe)||0)}catch{}let pref=0;try{pref=typeof preferenceScore==='function'?Number(preferenceScore(recipe)||0):0}catch{}return{recipe,hits,fit,pref,score:hits*100+fit*50-pref}}).filter(Boolean).sort((a,b)=>b.score-a.score).slice(0,3);return{...risk,recipes:matches}}).filter(x=>x.recipes.length)}
 window.autopilotV2Rescue=function(recipeId){try{if(typeof startCook==='function'){startCook(recipeId);return}}catch{}try{if(typeof showPanel==='function')showPanel('search')}catch{}};
 function addShoppingSuggestions(days=30,windowId=null){const windows=shoppingWindows(days),chosen=windowId?windows.find(w=>w.id===windowId):null,candidates=chosen?chosen.items:shoppingCandidates(days);if(!candidates.length)return 0;let list;try{list=typeof shopping!=='undefined'&&Array.isArray(shopping)?shopping:window.shopping}catch{return 0}if(!Array.isArray(list))return 0;for(const c of candidates){const existing=list.find(x=>x.autopilotV2Generated&&NORM(x.n)===NORM(c.name)&&!x.emergencyGenerated&&!x.reserveRotationGenerated),windowLabel=windows.find(w=>w.items.includes(c))?.label||'30-Tage-Prognose',meta={n:c.name,q:qty(c.amount,c.unit),autopilotGenerated:true,autopilotV2Generated:true,shoppingWindow:windowLabel,shoppingReasons:[`${windowLabel} · ${c.confidence==='high'?'hohe':'mittlere'} Datensicherheit`]};if(existing)Object.assign(existing,meta);else list.push(meta)}try{if(typeof saveShop==='function')saveShop();else localStorage.setItem('reserveShopping',JSON.stringify(list))}catch{}return candidates.length}
 window.autopilotV2AddShopping=function(windowId=null){const n=addShoppingSuggestions(30,windowId),b=document.getElementById(windowId?`autopilotV2Shop-${windowId}`:'autopilotV2Shop');if(b)b.textContent=n?`${n} Position${n===1?'':'en'} übernommen`:'Keine belastbaren Nachkäufe nötig'};
 function render(){const host=document.getElementById('home')||document.querySelector('main');if(!host)return;document.getElementById('autopilotV2')?.remove();const h=horizon(30),windows=shoppingWindows(30),rescues=rescueCandidates(7),box=document.createElement('div');box.id='autopilotV2';box.className='card';const reliable=h.items.filter(x=>x.reliable).length,buy=shoppingCandidates(30).length;box.innerHTML=`<h2>30-Tage-Ausblick</h2><p class="muted">RESERVE bündelt Nachkäufe und rettet Lebensmittel, bevor sie unnötig verderben.</p><div class="small"><b>${reliable}</b> belastbare Prognosen · <b>${rescues.length}</b> Rettungschancen · <b>${buy}</b> Nachkäufe in 7 Tagen</div>${rescues.map(r=>`<div class="item" style="margin-top:8px"><b>Zuerst verbrauchen: ${esc(r.name)}</b><div class="small muted">MHD in ca. ${Math.max(0,r.days)} Tagen · passende Rezepte:</div>${r.recipes.map(x=>`<button onclick="autopilotV2Rescue('${esc(x.recipe.id)}')">${esc(x.recipe.name)}</button>`).join('')}</div>`).join('')}${windows.map(w=>`<div class="item" style="margin-top:8px"><b>${esc(w.label)}</b><div class="small muted">${w.items.map(x=>esc(x.name)).join(' · ')}</div><button id="autopilotV2Shop-${w.id}" onclick="autopilotV2AddShopping('${w.id}')">Dieses Einkaufsfenster übernehmen</button></div>`).join('')||(!rescues.length?'<div class="small muted" style="padding-top:8px">Noch keine belastbaren Einkaufs- oder Rettungsvorschläge. RESERVE lernt weiter.</div>':'')}`;host.prepend(box)}
 window.RESERVE_AUTOPILOT_V2={version:'2.3',horizon,shoppingCandidates,shoppingWindows,rescueCandidates,addShoppingSuggestions,render};
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',render);else render();
})();