/* RESERVE barcode/product capture v2.1. OFF nutrition is source-backed; emergency suitability stays heuristic unless separately verified. */
(function(){
  let stream=null,scanTimer=null,lastProduct=null;
  const $=id=>document.getElementById(id);
  function categoryFor(name,categories){const s=N((name||'')+' '+(categories||''));if(/reis|pasta|nudel|brot|hafer|getreide/.test(s))return'Getreide & Beilagen';if(/gemuse|frucht|obst|tomat|brokk|kartoff|banan|apfel|beere/.test(s))return'Gemüse & Früchte';if(/fleisch|poulet|hahn|rind|fisch|ei|lins|kichererb/.test(s))return'Protein';if(/milch|joghurt|quark|kase|käse/.test(s))return'Milchprodukte';return'Sonstiges'}
  function quantityFromProduct(p){let q=(p.quantity||'').trim();if(q&&parseAmount(q))return q;let v=Number(p.product_quantity),u=(p.product_quantity_unit||'').toLowerCase();if(v>0){if(u==='kg')return fmt(v*1000,'g');if(u==='g')return fmt(v,'g');if(u==='l')return fmt(v*1000,'ml');if(u==='ml')return fmt(v,'ml')}return''}
  const finite=x=>{x=Number(x);return Number.isFinite(x)&&x>=0?x:null};
  function nutritionFromProduct(p){const n=p.nutriments||{},kcal=finite(n['energy-kcal_100g']),protein=finite(n.proteins_100g),carbs=finite(n.carbohydrates_100g),fat=finite(n.fat_100g),fiber=finite(n.fiber_100g),salt=finite(n.salt_100g);return{kcalPer100:kcal,proteinPer100:protein,carbsPer100:carbs,fatPer100:fat,fiberPer100:fiber,saltPer100:salt,basis:'100g',verified:kcal!=null,source:kcal!=null?'openfoodfacts':null}}
  function emergencyMeta(p,nutrition){if(nutrition.kcalPer100==null)return null;return{label:'Nährwertdaten',kcalPer100:nutrition.kcalPer100,nutritionVerified:true,nutritionSource:'openfoodfacts',nutritionBasis:'100g',suitabilityVerified:false}}
  async function lookup(code){code=(code||'').replace(/\D/g,'');if(!code)return showStatus('Bitte Barcode eingeben.','bad');showStatus('Produkt wird gesucht…','');try{const fields='code,product_name,product_name_de,brands,quantity,product_quantity,product_quantity_unit,categories_tags,categories,nutriments,nutrition_data_per';const r=await fetch('https://world.openfoodfacts.org/api/v2/product/'+encodeURIComponent(code)+'.json?fields='+fields,{headers:{'Accept':'application/json'}});if(!r.ok)throw new Error('HTTP '+r.status);const d=await r.json();if(!d||d.status!==1||!d.product){lastProduct=null;renderProduct(null,code);return}const p=d.product,name=(p.product_name_de||p.product_name||'').trim()||('Produkt '+code),qty=quantityFromProduct(p),cat=categoryFor(name,p.categories),nutrition=nutritionFromProduct(p);lastProduct={code,name,qty,cat,nutrition,emergency:emergencyMeta(p,nutrition)};renderProduct(lastProduct,code)}catch(e){lastProduct=null;showStatus('Produktdaten konnten nicht geladen werden. Du kannst den Artikel trotzdem manuell erfassen.','bad')}}
  function renderProduct(p,code){const box=$('barcodeResult');if(!box)return;if(!p){box.innerHTML=`<div class="missing-card"><div><b>Barcode ${code} nicht gefunden</b><div class="small">Name und Menge können unten manuell ergänzt werden.</div></div></div>`;$('scanName').value='';$('scanQty').value='';return}const n=p.nutrition||{},nutrition=n.kcalPer100!=null?`<div class="small">${Math.round(n.kcalPer100)} kcal / 100 g${n.proteinPer100!=null?' · '+n.proteinPer100+' g Protein':''}${n.carbsPer100!=null?' · '+n.carbsPer100+' g KH':''}${n.fatPer100!=null?' · '+n.fatPer100+' g Fett':''}</div><div class="small muted">Nährwerte: Open Food Facts. Notvorrat-Eignung wird separat und konservativ bewertet.</div>`:'<div class="small muted">Keine verwertbaren Nährwerte gefunden.</div>';box.innerHTML=`<div class="available-card"><b>${p.name}</b><div class="small">${p.qty||'Menge nicht erkannt'} · ${p.cat}</div>${nutrition}</div>`;$('scanName').value=p.name;$('scanQty').value=p.qty;$('scanCat').value=p.cat;showStatus(n.kcalPer100!=null?'Produkt und Nährwerte erkannt. Notvorrat-Eignung wird separat bewertet.':'Produkt erkannt.','good')}
  function showStatus(text,type){const el=$('barcodeStatus');if(!el)return;el.className='small '+(type==='bad'?'bad':type==='good'?'good':'muted');el.textContent=text}
  function addProduct(){const name=$('scanName').value.trim(),qty=$('scanQty').value.trim(),expiry=$('scanExpiry').value,cat=$('scanCat').value;if(!name||!qty||!parseAmount(qty)){showStatus('Bitte Produktname und eine gültige Menge eintragen, z. B. 500 g.','bad');return}const row={n:name,q:qty,e:expiry,c:cat,barcode:lastProduct?.code||$('barcodeInput').value.replace(/\D/g,'')};if(lastProduct?.nutrition?.source)row.nutrition=lastProduct.nutrition;if(lastProduct?.emergency)row.emergency=lastProduct.emergency;stock.push(row);localStorage.setItem('reserveStock',JSON.stringify(stock));$('scanName').value=$('scanQty').value=$('scanExpiry').value='';$('barcodeInput').value='';lastProduct=null;$('barcodeResult').innerHTML='';showStatus('Zum Vorrat hinzugefügt.','good');refresh()}
  async function startCamera(){if(!('BarcodeDetector'in window)||!navigator.mediaDevices?.getUserMedia){showStatus('Kamera-Barcodeerkennung wird von diesem Browser nicht unterstützt. Nutze die manuelle Barcode-Eingabe.','bad');return}try{const formats=await BarcodeDetector.getSupportedFormats();const wanted=['ean_13','ean_8','upc_a','upc_e'].filter(x=>formats.includes(x));const detector=new BarcodeDetector({formats:wanted.length?wanted:formats});stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}}});const v=$('barcodeVideo');v.srcObject=stream;v.style.display='block';await v.play();$('startScan').style.display='none';$('stopScan').style.display='inline-block';const scan=async()=>{if(!stream)return;try{const codes=await detector.detect(v);if(codes.length){const code=codes[0].rawValue;stopCamera();$('barcodeInput').value=code;lookup(code);return}}catch(e){}scanTimer=setTimeout(scan,350)};scan()}catch(e){showStatus('Kamera konnte nicht gestartet werden. Prüfe die Berechtigung oder nutze die manuelle Eingabe.','bad')}}
  function stopCamera(){if(scanTimer)clearTimeout(scanTimer);scanTimer=null;if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}const v=$('barcodeVideo');if(v){v.pause();v.srcObject=null;v.style.display='none'}if($('startScan'))$('startScan').style.display='inline-block';if($('stopScan'))$('stopScan').style.display='none'}
  function mount(){const section=$('stock');if(!section||$('barcodeCard'))return;const card=document.createElement('div');card.className='card';card.id='barcodeCard';card.innerHTML=`<h2>Produkt scannen</h2><p class="muted">Barcode scannen oder Nummer eingeben. RESERVE lädt Produktname, Packungsmenge und – sofern vorhanden – Nährwerte. Krisen-Eignung wird davon getrennt bewertet.</p><div class="grid2"><input id="barcodeInput" inputmode="numeric" placeholder="EAN / UPC Barcode"><button id="barcodeLookup">Produkt suchen</button></div><div><button id="startScan">Kamera starten</button> <button id="stopScan" class="secondary" style="display:none">Kamera stoppen</button></div><video id="barcodeVideo" playsinline muted style="display:none;width:100%;max-height:320px;object-fit:cover;border-radius:14px;margin-top:10px"></video><p id="barcodeStatus" class="small muted"></p><div id="barcodeResult"></div><div class="grid2"><input id="scanName" placeholder="Produktname"><input id="scanQty" placeholder="Menge, z. B. 500 g"></div><div class="grid2"><input id="scanExpiry" type="date"><select id="scanCat"><option>Getreide & Beilagen</option><option>Gemüse & Früchte</option><option>Protein</option><option>Milchprodukte</option><option>Sonstiges</option></select></div><button id="scanAdd">Zum Vorrat hinzufügen</button>`;section.insertBefore(card,section.children[1]||null);$('barcodeLookup').onclick=()=>lookup($('barcodeInput').value);$('barcodeInput').addEventListener('keydown',e=>{if(e.key==='Enter')lookup(e.target.value)});$('startScan').onclick=startCamera;$('stopScan').onclick=stopCamera;$('scanAdd').onclick=addProduct;document.addEventListener('visibilitychange',()=>{if(document.hidden)stopCamera()})}
  window.RESERVE_BARCODE={version:'2.1',lookup,startCamera,stopCamera,nutritionFromProduct,emergencyMeta};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
})();