/* RESERVE barcode/product capture v2.7 — multipack-aware scan-to-inventory. */
(function(){
let stream=null,lastProduct=null;const $=id=>document.getElementById(id),MEMORY_KEY='reserveBarcodeProductsV1';
function mem(){try{return JSON.parse(localStorage.getItem(MEMORY_KEY)||'{}')}catch{return{}}}function remember(code,p){if(!code||!p?.name)return;const m=mem();m[code]={code,name:p.name,qty:p.qty||'',cat:p.cat||'Sonstiges',rememberedAt:new Date().toISOString()};localStorage.setItem(MEMORY_KEY,JSON.stringify(m))}
function qty(value){const multi=window.RESERVE_MULTIPACK?.parse?.(value);if(multi)return multi;return window.parseAmount?.(value)||null}function format(p){return window.RESERVE_MULTIPACK?.format?.(p)||(window.fmt?.(p.v,p.u))||`${p.v} ${p.u}`}
async function lookup(code){code=String(code||'').replace(/\D/g,'');if(!code)return;const known=mem()[code];if(known){lastProduct={...known,fromMemory:true};fill(lastProduct);return}try{const r=await fetch('https://world.openfoodfacts.org/api/v2/product/'+code+'.json?fields=code,product_name,product_name_de,quantity,categories');const d=await r.json();if(d?.status===1){const p=d.product||{},name=(p.product_name_de||p.product_name||'Produkt '+code).trim();lastProduct={code,name,qty:p.quantity||'',cat:'Sonstiges'};fill(lastProduct)}}catch{status('Produktdaten konnten nicht geladen werden. Manuelle Erfassung ist möglich.','bad')}}
function fill(p){$('scanName').value=p.name||'';$('scanQty').value=p.qty||'';if(p.cat)$('scanCat').value=p.cat;status('Lebensmittel erkannt.','good')}
function status(t,c='muted'){const e=$('barcodeStatus');if(e){e.className='small '+c;e.textContent=t}}
function addProduct(){const name=$('scanName').value.trim(),raw=$('scanQty').value.trim(),p=qty(raw),expiry=$('scanExpiry').value,cat=$('scanCat').value,code=(lastProduct?.code||$('barcodeInput').value).replace(/\D/g,'');if(!name||!p||p.v<=0){status('Bitte Produktname und gültige Menge eintragen, z. B. 500 g oder 6 × 1,5 l.','bad');return}const normalized=format(p),now=new Date().toISOString();let existing=stock.find(s=>{const hp=qty(s.q);return (code?String(s.barcode||'')===code:String(s.n).toLowerCase()===name.toLowerCase())&&(s.e||'')===expiry&&hp&&hp.u===p.u});if(existing){const hp=qty(existing.q);existing.q=format({v:hp.v+p.v,u:p.u});existing.updatedAt=now}else stock.push({n:name,q:normalized,e:expiry,c:cat,barcode:code,captureSource:'barcode',capturedAt:now,multipack:p.multipack?{count:p.count,total:normalized,original:raw}:undefined});localStorage.setItem('reserveStock',JSON.stringify(stock));if(code)remember(code,{name,qty:raw,cat});$('scanName').value=$('scanQty').value=$('scanExpiry').value=$('barcodeInput').value='';lastProduct=null;status(existing?'Bestand aktualisiert.':'Zum Vorrat hinzugefügt.','good');window.refresh?.()}
async function startCamera(){status('Kamera-Scan bleibt verfügbar. Falls der Browser den Barcode nicht erkennt, Nummer manuell eingeben.');try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}}});const v=$('barcodeVideo');v.srcObject=stream;v.style.display='block';await v.play()}catch{status('Kamera konnte nicht gestartet werden. Barcode kann manuell eingegeben werden.','bad')}}function stopCamera(){if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}const v=$('barcodeVideo');if(v){v.srcObject=null;v.style.display='none'}}
function mount(){const section=$('stock');if(!section||$('barcodeCard'))return;const card=document.createElement('div');card.className='card';card.id='barcodeCard';card.innerHTML='<h2>Lebensmittel scannen</h2><p class="muted">Barcode scannen oder eingeben. Mehrfachpackungen werden als Gesamtbestand übernommen.</p><div class="grid2"><input id="barcodeInput" inputmode="numeric" placeholder="EAN / UPC Barcode"><button id="barcodeLookup">Produkt suchen</button></div><button id="startScan">Kamera starten</button> <button id="stopScan" class="secondary">Kamera stoppen</button><video id="barcodeVideo" playsinline muted style="display:none;width:100%;max-height:320px"></video><p id="barcodeStatus" class="small muted"></p><div id="barcodeResult"></div><div class="grid2"><input id="scanName" placeholder="Lebensmittelname"><input id="scanQty" placeholder="Menge, z. B. 500 g oder 6 × 1,5 l"></div><div class="grid2"><input id="scanExpiry" type="date"><select id="scanCat"><option>Getreide & Beilagen</option><option>Gemüse & Früchte</option><option>Protein</option><option>Milchprodukte</option><option>Sonstiges</option></select></div><button id="scanAdd">Zum Vorrat hinzufügen</button>';section.insertBefore(card,section.children[1]||null);$('barcodeLookup').onclick=()=>lookup($('barcodeInput').value);$('scanAdd').onclick=addProduct;$('startScan').onclick=startCamera;$('stopScan').onclick=stopCamera}
window.RESERVE_BARCODE={version:'2.7',lookup,addProduct,startCamera,stopCamera,remembered:c=>mem()[String(c||'')]||null,remember,parseQuantity:qty};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
})();