/* RESERVE emergency v2 — household reserve targets, protected reserve and shopping integration; orientation based on Swiss BWL recommendations. */
(function(){
 const KEY='reserveEmergencyV2',LEGACY='reserveEmergencyV1';
 const load=()=>{try{const v=localStorage.getItem(KEY)||localStorage.getItem(LEGACY)||'{}';return JSON.parse(v)}catch{return{}}};
 const save=x=>localStorage.setItem(KEY,JSON.stringify(x));
 const num=x=>Math.max(0,Number(x)||0),clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
 const people=()=>Math.max(1,persons()),targetDays=d=>clamp(Math.round(num(d.targetDays)||7),3,14);
 function emergencyRecipes(){return (window.recipes||[]).filter(r=>(!r.status||r.status==='approved')&&r.resilience)}
 function capability(){const rs=emergencyRecipes();return {known:rs.length,noCook:rs.filter(r=>r.resilience.noCook).length,noPower:rs.filter(r=>r.resilience.power==='none').length,noFridge:rs.filter(r=>r.resilience.refrigeration==='none').length}}
 function foodDays(){try{const x=buildShoppingPlan();return Math.min(targetDays(load()),x.plan.filter(Boolean).length)}catch{return 0}}
 function reserveTargets(d){const p=people(),days=targetDays(d);return {people:p,days,water:p*9,meals:p*days*3}}
 function shoppingNeeds(){const d=load(),t=reserveTargets(d),needs=[],water=num(d.water),meals=num(d.shelfMeals);if(water<t.water)needs.push({n:'Trinkwasser / Notwasser',q:`${Math.ceil((t.water-water)*2)/2} l`,emergencyGenerated:true});if(meals<t.meals)needs.push({n:'Haltbare Notmahlzeiten',q:`${Math.ceil(t.meals-meals)} Portionen`,emergencyGenerated:true});return needs}
 function addEmergencyShopping(){const needs=shoppingNeeds();if(!Array.isArray(window.shopping))return 0;for(let i=shopping.length-1;i>=0;i--)if(shopping[i]?.emergencyGenerated)shopping.splice(i,1);needs.forEach(x=>shopping.push(x));if(typeof saveShop==='function')saveShop();if(typeof renderShop==='function')renderShop();return needs.length}
 function protectedReserve(){const d=load(),t=reserveTargets(d),water=num(d.water),meals=num(d.shelfMeals);return {enabled:d.protect!==false,targetDays:t.days,waterTarget:t.water,water,waterGap:Math.max(0,t.water-water),mealTarget:t.meals,shelfMeals:meals,mealGap:Math.max(0,t.meals-meals),safe:water>=t.water&&meals>=t.meals}}
 function ensurePanel(){if(document.getElementById('emergency'))return;const main=document.querySelector('main');if(!main)return;const s=document.createElement('section');s.id='emergency';s.className='panel';s.innerHTML=`<div class="card emergency-card"><div class="official-note"><b>Notvorrat · Orientierung an BWL-Empfehlungen</b><br><span class="small muted">Keine Zertifizierung oder Prüfung durch den Bund. RESERVE hilft dir, deinen privaten Vorrat anhand der veröffentlichten Empfehlungen zu organisieren.</span></div><h2>Meine Krisenvorsorge</h2><div id="emergencyView"></div></div>`;main.appendChild(s);const nav=document.querySelector('nav');if(nav&&!document.getElementById('emergencyTab')){const b=document.createElement('button');b.id='emergencyTab';b.className='tab emergency-tab';b.textContent='Notvorrat';b.onclick=function(){show('emergency',this);renderEmergency()};nav.insertBefore(b,nav.lastElementChild)}}
 function check(label,key,data){return `<label class="emergency-check"><input type="checkbox" data-ekey="${key}" ${data[key]?'checked':''}><span>${label}</span></label>`}
 window.renderEmergency=function(){ensurePanel();const el=document.getElementById('emergencyView');if(!el)return;const d=load(),t=reserveTargets(d),water=num(d.water),shelfMeals=num(d.shelfMeals),waterPct=Math.min(100,Math.round(water/t.water*100)),days=foodDays(),foodPct=Math.min(100,Math.round(days/t.days*100)),mealPct=Math.min(100,Math.round(shelfMeals/t.meals*100)),checks=['radio','light','batteries','cooking','medicine','cash','hygiene','readyFood'],done=checks.filter(k=>d[k]).length,overall=Math.round((waterPct+foodPct+mealPct+(done/checks.length*100))/4),cap=capability(),needs=shoppingNeeds();
 el.innerHTML=`<div class="emergency-score"><div><span>Vorsorgegrad</span><b>${overall}%</b></div><div><span>Wasser</span><b>${waterPct}%</b></div><div><span>Notmahlzeiten</span><b>${mealPct}%</b></div></div><div class="emergency-progress"><i style="width:${overall}%"></i></div><div class="emergency-box"><h3>🏠 Haushaltsziel</h3><p><b>${t.people} ${t.people===1?'Person':'Personen'} · ${t.days} Tage</b></p><label class="small">Zielzeitraum <input id="emergencyDays" type="number" min="3" max="14" value="${t.days}"></label><label class="emergency-check"><input id="protectEmergency" type="checkbox" ${d.protect!==false?'checked':''}><span>Strategische Reserve schützen</span></label><p class="small muted">Wenn aktiviert, kann der Autopilot diese Zielwerte berücksichtigen und vor einer Unterschreitung warnen.</p></div><div class="emergency-grid"><div class="emergency-box"><h3>💧 Wasser</h3><p><b>${water} / ${t.water} Liter</b></p><p class="small muted">BWL-Empfehlung: mindestens 9 Liter pro Person für Trinken und Kochen während drei Tagen.</p><input id="emergencyWater" type="number" min="0" step="0.5" value="${water}" placeholder="Liter Wasser vorhanden"></div><div class="emergency-box"><h3>🥫 Haltbare Mahlzeiten</h3><p><b>${shelfMeals} / ${t.meals} Portionen</b></p><input id="emergencyMeals" type="number" min="0" step="1" value="${shelfMeals}" placeholder="Haltbare Portionen vorhanden"><p class="small muted">RESERVE-Zielwert: drei Mahlzeiten pro Person und Tag als einfache Planungsgrösse.</p></div></div><button onclick="saveEmergencyTargets()">Notvorrat speichern</button><div class="emergency-box"><h3>⚡ Krisentaugliche Rezepte</h3><p><b>${cap.noCook}</b> ohne Kochen · <b>${cap.noPower}</b> ohne Strom · <b>${cap.noFridge}</b> ohne Kühlung</p><p class="small muted">Nur Rezepte mit geprüften Resilienz-Metadaten werden hier gezählt.</p></div><div class="emergency-box"><h3>🛒 Lücke zum Ziel</h3>${needs.length?needs.map(x=>`<p class="small"><b>${x.n}</b> · ${x.q}</p>`).join(''):'<p class="small">Deine erfassten Zielmengen sind erreicht.</p>'}<button onclick="addEmergencyNeeds()" ${needs.length?'':'disabled'}>Fehlende Reserve → Einkaufsliste</button></div><h3>Stromausfall & Grundausstattung</h3><div class="emergency-checks">${check('Sofort konsumierbare Lebensmittel vorhanden','readyFood',d)}${check('Batterie-/Autoradio vorhanden','radio',d)}${check('Taschenlampe / stromunabhängiges Licht','light',d)}${check('Ersatzbatterien vorhanden','batteries',d)}${check('Stromunabhängige Kochmöglichkeit','cooking',d)}${check('Persönliche Medikamente / Hausapotheke für mindestens 1 Woche','medicine',d)}${check('Etwas Bargeld in kleinen Scheinen','cash',d)}${check('Benötigte Hygieneartikel vorhanden','hygiene',d)}</div><div class="official-note small">Lebensmittelabdeckung und Mahlzeitenziel sind RESERVE-Planungswerte. Sie ersetzen nicht den persönlichen Notvorrats-Rechner des BWL.</div>`;
 el.querySelectorAll('[data-ekey]').forEach(x=>x.onchange=()=>{const q=load();q[x.dataset.ekey]=x.checked;save(q);renderEmergency()})};
 window.saveEmergencyTargets=function(){const d=load();d.water=num(document.getElementById('emergencyWater')?.value);d.shelfMeals=Math.round(num(document.getElementById('emergencyMeals')?.value));d.targetDays=targetDays({targetDays:document.getElementById('emergencyDays')?.value});d.protect=!!document.getElementById('protectEmergency')?.checked;save(d);renderEmergency()};
 window.saveEmergencyWater=window.saveEmergencyTargets;
 window.addEmergencyNeeds=function(){const n=addEmergencyShopping();renderEmergency();return n};
 window.RESERVE_EMERGENCY={load,targets:()=>reserveTargets(load()),protectedReserve,shoppingNeeds,capability,addEmergencyShopping};
 const oldShow=window.show;window.show=function(id,btn){oldShow(id,btn);if(id==='emergency')renderEmergency()};const oldRefresh=window.refresh;window.refresh=function(){oldRefresh();if(document.getElementById('emergency'))renderEmergency()};function boot(){ensurePanel();renderEmergency()}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
