/* RESERVE expiry UI + recommendations v1.0 */
(function(){
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const getStock=()=>{try{return stock}catch{return[]}},getRecipes=()=>{try{return recipes}catch{return[]}};
  function ensureCard(){const list=document.getElementById('stockList');if(!list)return null;let card=document.getElementById('expiryIntelligence');if(!card){card=document.createElement('div');card.id='expiryIntelligence';card.className='card quality';list.parentNode.insertBefore(card,list)}return card}
  function recipeMatches(){if(!window.RESERVE_EXPIRY)return[];const expiring=window.RESERVE_EXPIRY.expiringWithin(7,getStock()).map(x=>x.row).filter(r=>window.RESERVE_EXPIRY.expiryState(r).state!=='expired');if(!expiring.length)return[];const keys=expiring.map(x=>window.N?window.N(x.n):String(x.n).toLowerCase());return getRecipes().map(r=>{const ingredients=r.ingredients||[];const hits=ingredients.filter(i=>keys.some(k=>{const n=window.N?window.N(i.name):String(i.name).toLowerCase();return n.includes(k)||k.includes(n)}));return{r,hits}}).filter(x=>x.hits.length).sort((a,b)=>b.hits.length-a.hits.length).slice(0,3)}
  function shoppingForecast(){try{return window.RESERVE_PANTRY_INTELLIGENCE?.nextShoppingTrip?.(30)||null}catch{return null}}
  function render(){const card=ensureCard();if(!card||!window.RESERVE_EXPIRY)return;const sorted=window.RESERVE_EXPIRY.sorted(getStock()),critical=sorted.filter(x=>['expired','today','urgent','soon'].includes(x.expiry.state)),matches=recipeMatches(),trip=shoppingForecast();const expiryHtml=critical.length?critical.slice(0,8).map(x=>`<div class="item"><b>${esc(x.row.n)}</b> · ${esc(x.row.q)} <span class="pill ${x.expiry.state==='expired'||x.expiry.state==='today'?'bad':''}">${esc(x.expiry.label)}</span>${x.expiry.state==='expired'?'<div class="small muted">Nicht als Menüempfehlung verwendet. Zustand prüfen.</div>':`<button class="secondary" onclick="RESERVE_EXPIRY_UI.consumeAll(${x.index})">Als verbraucht buchen</button>`}</div>`).join(''):'<span class="pill good">Keine Vorräte laufen in den nächsten 7 Tagen ab.</span>';const recipeHtml=matches.length?matches.map(x=>`<div class="item"><b>${esc(x.r.name)}</b><div class="small muted">Verbraucht zuerst: ${x.hits.map(h=>esc(h.name)).join(', ')}</div><button class="secondary" onclick="startCook('${esc(x.r.id)}')">Menü öffnen</button></div>`).join(''):'<p class="small muted">Aktuell keine passenden Ablauf-Menüempfehlungen.</p>';const tripHtml=trip?.items?.length?`<div class="item"><b>Verbrauchsprognose: nächster Einkauf ${esc(trip.date||'')}</b><div class="small muted">${trip.items.slice(0,5).map(x=>`${esc(x.name)}: ${esc(x.buyAmount||'')}`).join(' · ')}</div>${window.RESERVE_PANTRY_INTELLIGENCE?.applyNextTrip?'<button class="secondary" onclick="RESERVE_EXPIRY_UI.applyForecast()">Prognose auf Einkaufsliste</button>':''}</div>`:'<p class="small muted">Für eine Nachkaufprognose werden weitere Verbrauchsdaten gesammelt.</p>';card.innerHTML=`<h3>Haltbarkeit & Verbrauch</h3><div class="small muted">RESERVE priorisiert Ablaufdaten und verbindet sie mit Menü- und Nachkaufempfehlungen.</div><h3>Zuerst verbrauchen</h3>${expiryHtml}<h3>Passende Menüs</h3>${recipeHtml}<h3>Automatischer Nachkauf</h3>${tripHtml}`}
  function consumeAll(index){const row=getStock()[index],p=row&&window.parseAmount?.(row.q);if(!p)return false;const result=window.RESERVE_EXPIRY.consume(index,p.v,'expiry-ui');render();return !!result.ok}
  function applyForecast(){const n=window.RESERVE_PANTRY_INTELLIGENCE?.applyNextTrip?.()||0;window.refresh?.();render();return n}
  const oldRefresh=window.refresh;window.refresh=function(){const r=oldRefresh?.apply(this,arguments);render();return r};
  window.RESERVE_EXPIRY_UI={version:'1.0',render,recipeMatches,consumeAll,applyForecast};
  setTimeout(render,0);
})();