/* RESERVE expiry UI + recommendations v1.0 */
(function(){
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const getStock=()=>{try{return stock}catch{return[]}},getRecipes=()=>{try{return recipes}catch{return[]}};
  function ensureCard(){const list=document.getElementById('stockList');if(!list)return null;let card=document.getElementById('expiryIntelligence');if(!card){card=document.createElement('div');card.id='expiryIntelligence';card.className='card quality';list.parentNode.insertBefore(card,list)}return card}
  function recipeMatches(){if(!window.RESERVE_EXPIRY)return[];const expiring=window.RESERVE_EXPIRY.expiringWithin(7,getStock()).map(x=>x.row).filter(r=>window.RESERVE_EXPIRY.expiryState(r).state!=='expired');if(!expiring.length)return[];const keys=expiring.map(x=>window.N?window.N(x.n):String(x.n).toLowerCase());return getRecipes().map(r=>{const ingredients=r.ingredients||[];const hits=ingredients.filter(i=>keys.some(k=>{const n=window.N?window.N(i.name):String(i.name).toLowerCase();return n.includes(k)||k.includes(n)}));return{r,hits}}).filter(x=>x.hits.length).sort((a,b)=>b.hits.length-a.hits.length).slice(0,3)}
  function shoppingForecast(){try{return window.RESERVE_PANTRY_INTELLIGENCE?.nextShoppingTrip?.(30)||null}catch{return null}}
  function render(){const card=ensureCard();if(!card||!window.RESERVE_EXPIRY)return;const sorted=window.RESERVE_EXPIRY.sorted(getStock()),seen=new Set(),critical=sorted.filter(x=>['expired','today','urgent','soon'].includes(x.expiry.state)).filter(x=>{const key=x.row.barcode?'barcode:'+x.row.barcode:'name:'+String(x.row.n).toLowerCase();if(seen.has(key))return false;seen.add(key);return true}),matches=recipeMatches(),trip=shoppingForecast(),v=window.RESERVE_VISUAL_FLOW;card.hidden=!critical.length&&!matches.length&&!trip?.items?.length;if(card.hidden){card.innerHTML='';return}card.innerHTML=(critical.length?`<h3>Bald prüfen</h3><div class="reserve-action-grid">${critical.slice(0,8).map(x=>v?.product?.(x.row,x.index,x.expiry.state==='expired'?'MHD überschritten':x.expiry.label,x.expiry.state==='expired')||`<div class="item">${esc(x.row.n)} · ${esc(x.expiry.label)}</div>`).join('')}</div>`:'')+(matches.length?`<h3>Dazu kochen</h3><div class="reserve-action-grid">${matches.map(x=>v?.recipe?.(x.r)||`<button class="secondary" onclick="startCook('${esc(x.r.id)}')">${esc(x.r.name)}</button>`).join('')}</div>`:'')+(trip?.items?.length?`<h3>Bald nachkaufen</h3><div class="reserve-action-grid">${trip.items.slice(0,4).map(x=>{const index=getStock().findIndex(s=>s.n===x.name),row=getStock()[index]||{n:x.name,q:''};return v?.product?.(row,index,'Bis '+String(x.buyBy||trip.date||'').split('-').reverse().join('.'))||esc(x.name)}).join('')}</div><button class="secondary" onclick="RESERVE_EXPIRY_UI.applyForecast()">Zur Einkaufsliste</button>`:'');window.RESERVE_PRODUCT_IMAGES?.apply?.()}
  function consumeAll(index){const row=getStock()[index],p=row&&window.parseAmount?.(row.q);if(!p)return false;const result=window.RESERVE_EXPIRY.consume(index,p.v,'expiry-ui');render();return !!result.ok}
  function applyForecast(){const n=window.RESERVE_PANTRY_INTELLIGENCE?.applyNextTrip?.()||0;window.refresh?.();render();return n}
  const oldRefresh=window.refresh;window.refresh=function(){const r=oldRefresh?.apply(this,arguments);render();return r};
  window.RESERVE_EXPIRY_UI={version:'1.0',render,recipeMatches,consumeAll,applyForecast};
  setTimeout(render,0);
})();