/* RESERVE core v3: batches/FEFO, purchase->pantry, guided cooking, preferences. */
(function(){
  const unitOf=i=>(i.unit||'').toLowerCase()==='stück'?'stück':i.unit;
  const parseDate=s=>s?new Date(s+'T00:00:00').getTime():Number.MAX_SAFE_INTEGER;
  function matchName(a,b){a=N(a);b=N(b);return a===b||a.includes(b)||b.includes(a)}
  function batches(name){return stock.filter(s=>matchName(s.n,name)).map((s,index)=>({s,index,p:parseAmount(s.q)})).filter(x=>x.p).sort((a,b)=>parseDate(a.s.e)-parseDate(b.s.e));}
  function available(name,unit){unit=(unit||'').toLowerCase()==='stück'?'stück':unit;return batches(name).filter(x=>x.p.u===unit).reduce((n,x)=>n+x.p.v,0)}
  function consume(name,amount,unit){unit=(unit||'').toLowerCase()==='stück'?'stück':unit;let left=amount;for(const b of batches(name)){if(left<=0)break;if(b.p.u!==unit)continue;const take=Math.min(left,b.p.v);b.p.v-=take;left-=take;b.s.q=fmt(b.p.v,b.p.u)}stock=stock.filter(s=>{const p=parseAmount(s.q);return !p||p.v>0});return left}
  window.stockBatches=batches;window.availableAmount=available;
  window.need=function(r,i){const req=i.amount*persons(),u=unitOf(i);return Math.max(0,req-available(i.name,u))};
  window.stockEntry=function(name){const b=batches(name);return b.length?b[0].s:null};
  window.finishCook=function(id){const base=recipes.find(x=>x.id===id);if(!base)return;const r=adaptRecipe(base);if(missing(r).length)return;r.ingredients.forEach(i=>consume(i.name,i.amount*persons(),unitOf(i)));localStorage.setItem('reserveStock',JSON.stringify(stock));localStorage.removeItem('reserveCookProgress:'+id);refresh();renderCook()};
  window.renderStock=function(){
    if(!stock.length){stockList.innerHTML='<p class="muted">Noch nichts im Vorrat.</p>';return}
    const groups=[];
    stock.forEach((s,i)=>{let g=groups.find(x=>matchName(x.name,s.n));if(!g){g={name:s.n,rows:[]};groups.push(g)}g.rows.push({s,i})});
    stockList.innerHTML=groups.map(g=>{const totals={};g.rows.forEach(x=>{const p=parseAmount(x.s.q);if(p)totals[p.u]=(totals[p.u]||0)+p.v});const total=Object.entries(totals).map(([u,v])=>fmt(v,u)).join(' + ');return `<div class="item"><b>${g.name}</b> · ${total}<div class="small muted">${g.rows.sort((a,b)=>parseDate(a.s.e)-parseDate(b.s.e)).map(x=>`${x.s.q}${x.s.e?' · MHD '+x.s.e:''}`).join('<br>')}</div>${g.rows.map(x=>`<button class="secondary" onclick="stock.splice(${x.i},1);saveStock()">Charge entfernen</button>`).join('')}</div>`}).join('')
  };
  function addToPantry(item){const p=parseAmount(item.q);if(!p)return false;stock.push({n:item.n,q:fmt(p.v,p.u),e:'',c:'Sonstiges'});return true}
  window.purchaseToStock=function(index){const item=shopping[index];if(!item)return;if(!addToPantry(item))return;shopping.splice(index,1);localStorage.setItem('reserveStock',JSON.stringify(stock));localStorage.setItem('reserveShopping',JSON.stringify(shopping));refresh()};
  const baseRenderShop=window.renderShop;
  window.renderShop=function(){if(window.normalizeShopping)normalizeShopping();if(!shopping.length){shopList.innerHTML='<p class="muted">Einkaufsliste ist leer.</p>';return}shopList.innerHTML=shopping.map((s,i)=>`<div class="shop"><b>${s.n}</b>${s.q?' · '+s.q:''}<div><button onclick="purchaseToStock(${i})" ${s.q?'':'disabled'}>Gekauft → Vorrat</button> <button class="secondary" onclick="shopping.splice(${i},1);saveShop()">Entfernen</button></div></div>`).join('')};
  function profileExtended(){const p=profile();if(!p.goal)p.goal='Vorrat zuerst';if(!p.maxMinutes)p.maxMinutes=60;return p}
  function injectProfileControls(){const card=document.querySelector('#profile .card');if(!card||document.getElementById('goal'))return;const btn=card.querySelector('button');const box=document.createElement('div');box.innerHTML=`<div class="grid2"><select id="goal"><option>Vorrat zuerst</option><option>Schnell</option><option>Proteinreich</option><option>Ballaststoffreich</option><option>Kalorienärmer</option></select><input id="maxMinutes" type="number" min="5" max="180" step="5" placeholder="Max. Kochzeit in Minuten"></div>`;card.insertBefore(box,btn);const p=profileExtended();goal.value=p.goal;maxMinutes.value=p.maxMinutes}
  window.saveProfile=function(){const old=profileExtended();localStorage.setItem('reserveProfile',JSON.stringify({people:Math.max(1,+people.value||1),diet:diet.value,avoid:avoid.value,dislikes:dislikes.value,goal:document.getElementById('goal')?.value||old.goal,maxMinutes:Math.max(5,+document.getElementById('maxMinutes')?.value||60)}));saved.textContent='Gespeichert.';refresh()};
  function expiryUrgency(r){let best=Number.MAX_SAFE_INTEGER;adaptRecipe(r).ingredients.forEach(i=>batches(i.name).forEach(b=>best=Math.min(best,parseDate(b.s.e))));return best}
  function preferenceScore(r){const p=profileExtended(),mins=(r.prepMinutes||0)+(r.cookMinutes||0);if(mins>p.maxMinutes)return 1e9;let score=0;if(p.goal==='Schnell')score+=mins;if(p.goal==='Proteinreich')score-=((r.nutrition||{}).protein||0)*2;if(p.goal==='Ballaststoffreich')score-=((r.nutrition||{}).fiber||0)*3;if(p.goal==='Kalorienärmer')score+=((r.nutrition||{}).kcal||0)/20;if(p.goal==='Vorrat zuerst'){const ex=expiryUrgency(r);score+=(ex===Number.MAX_SAFE_INTEGER?1e6:(ex-Date.now())/86400000)}return score}
  window.renderSmart=function(){let m=currentMeal(),pool=recipes.filter(r=>allowed(r)&&(r.mealTimes||[]).includes(m)&&preferenceScore(r)<1e9),ready=pool.filter(canCook).sort((a,b)=>preferenceScore(a)-preferenceScore(b)),near=pool.filter(r=>!canCook(r)).sort((a,b)=>(missingScore(a)+preferenceScore(a)/1000)-(missingScore(b)+preferenceScore(b)/1000)),list=(ready.length?ready:near).slice(0,4);timeLabel.textContent='Aktuell: '+m+' · '+profileExtended().goal;smartNow.innerHTML=list.length?`<div class="recipe-card-grid">${list.map(recipeCard).join('')}</div>`:'<p class="muted">Keine passenden Rezepte im gewählten Zeitlimit.</p>'};
  function progressKey(id){return 'reserveCookProgress:'+id}
  function cookProgress(id){try{return JSON.parse(localStorage.getItem(progressKey(id))||'[]')}catch{return[]}}
  window.toggleCookStep=function(id,i){let p=cookProgress(id);p[i]=!p[i];localStorage.setItem(progressKey(id),JSON.stringify(p));renderCook()};
  window.resetCookSteps=function(id){localStorage.removeItem(progressKey(id));renderCook()};
  window.renderCook=function(){let b=recipes.find(r=>r.id===cookRecipe.value);if(!b){cookView.innerHTML='';return}let r=adaptRecipe(b),d=missing(b),p=cookProgress(r.id),done=r.steps.filter((_,i)=>p[i]).length;cookView.innerHTML=`${recipeVisual(r)}<h2>${r.name}</h2><div class="portion"><b>${done}/${r.steps.length} Schritte erledigt · Mengen für ${persons()} ${persons()===1?'Person':'Personen'}</b></div>${d.length?`<div class="missing-card">${missingSentence(d)}<button onclick="addMissing('${r.id}')">+ Einkaufsliste</button></div>`:'<div class="available-card">✓ Alle Zutaten sind im Vorrat.</div>'}<h3>Zutaten</h3><div class="ingredient-grid">${r.ingredients.map(i=>`<div class="ingredient"><b>${i.name}</b><div>${fmt(i.amount*persons(),i.unit)}</div><div class="small muted">Verfügbar: ${fmt(available(i.name,unitOf(i)),unitOf(i))}</div></div>`).join('')}</div><h3>Zubereitung</h3>${r.steps.map((s,i)=>`<div class="step"><div class="stepno">${p[i]?'✓':i+1}</div><div style="flex:1;${p[i]?'opacity:.55;text-decoration:line-through':''}">${s}<br><button class="secondary" onclick="toggleCookStep('${r.id}',${i})">${p[i]?'Rückgängig':'Schritt erledigt'}</button></div></div>`).join('')}<button class="secondary" onclick="resetCookSteps('${r.id}')">Fortschritt zurücksetzen</button><button onclick="finishCook('${r.id}')" ${d.length||done<r.steps.length?'disabled':''}>Gericht gekocht · Vorrat aktualisieren</button>`};
  const oldRefresh=window.refresh;window.refresh=function(){oldRefresh();injectProfileControls();renderShop();renderStock()};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',injectProfileControls);else injectProfileControls();
})();
