/* RESERVE core v6: batches/FEFO, purchase->pantry, detailed cooking, shopping-aware weekly planning. */
(function(){
  const unitOf=i=>(i.unit||'').toLowerCase()==='stück'?'stück':i.unit;
  const parseDate=s=>s?new Date(s+'T00:00:00').getTime():Number.MAX_SAFE_INTEGER;
  const ingredientIcons={reis:'🍚',eier:'🥚',ei:'🥚',brokkoli:'🥦',poulet:'🍗',hähnchen:'🍗',haehnchen:'🍗',kartoffeln:'🥔',kartoffel:'🥔',tomaten:'🍅',tomate:'🍅',spinat:'🥬',paprika:'🫑',zucchini:'🥒',champignons:'🍄',apfel:'🍎',banane:'🍌',joghurt:'🥣',milch:'🥛',käse:'🧀',kaese:'🧀',brot:'🍞',vollkornbrot:'🍞',pasta:'🍝',spaghetti:'🍝',linsen:'🫘',kichererbsen:'🫘',lachs:'🐟'};
  function matchName(a,b){a=N(a);b=N(b);return a===b||a.includes(b)||b.includes(a)}
  function icon(name){return ingredientIcons[N(name)]||'🥣'}
  function batches(name){return stock.filter(s=>matchName(s.n,name)).map((s,index)=>({s,index,p:parseAmount(s.q)})).filter(x=>x.p).sort((a,b)=>parseDate(a.s.e)-parseDate(b.s.e));}
  function available(name,unit){unit=(unit||'').toLowerCase()==='stück'?'stück':unit;return batches(name).filter(x=>x.p.u===unit).reduce((n,x)=>n+x.p.v,0)}
  function consume(name,amount,unit){unit=(unit||'').toLowerCase()==='stück'?'stück':unit;let left=amount;for(const b of batches(name)){if(left<=0)break;if(b.p.u!==unit)continue;const take=Math.min(left,b.p.v);b.p.v-=take;left-=take;b.s.q=fmt(b.p.v,b.p.u)}stock=stock.filter(s=>{const p=parseAmount(s.q);return !p||p.v>0});return left}
  window.stockBatches=batches;window.availableAmount=available;
  window.need=function(r,i){const req=i.amount*persons(),u=unitOf(i);return Math.max(0,req-available(i.name,u))};
  window.stockEntry=function(name){const b=batches(name);return b.length?b[0].s:null};
  window.finishCook=function(id){const base=recipes.find(x=>x.id===id);if(!base)return;const r=adaptRecipe(base);if(missing(r).length)return;r.ingredients.forEach(i=>consume(i.name,i.amount*persons(),unitOf(i)));localStorage.setItem('reserveStock',JSON.stringify(stock));localStorage.removeItem('reserveCookProgress:'+id);refresh();renderCook()};
  window.renderStock=function(){if(!stock.length){stockList.innerHTML='<p class="muted">Noch nichts im Vorrat.</p>';return}const groups=[];stock.forEach((s,i)=>{let g=groups.find(x=>matchName(x.name,s.n));if(!g){g={name:s.n,rows:[]};groups.push(g)}g.rows.push({s,i})});stockList.innerHTML=groups.map(g=>{const totals={};g.rows.forEach(x=>{const p=parseAmount(x.s.q);if(p)totals[p.u]=(totals[p.u]||0)+p.v});const total=Object.entries(totals).map(([u,v])=>fmt(v,u)).join(' + ');return `<div class="item"><b>${g.name}</b> · ${total}<div class="small muted">${g.rows.sort((a,b)=>parseDate(a.s.e)-parseDate(b.s.e)).map(x=>`${x.s.q}${x.s.e?' · MHD '+x.s.e:''}`).join('<br>')}</div>${g.rows.map(x=>`<button class="secondary" onclick="stock.splice(${x.i},1);saveStock()">Charge entfernen</button>`).join('')}</div>`}).join('')};
  function addToPantry(item){const p=parseAmount(item.q);if(!p)return false;stock.push({n:item.n,q:fmt(p.v,p.u),e:'',c:'Sonstiges'});return true}
  window.purchaseToStock=function(index){const item=shopping[index];if(!item)return;if(!addToPantry(item))return;shopping.splice(index,1);localStorage.setItem('reserveStock',JSON.stringify(stock));localStorage.setItem('reserveShopping',JSON.stringify(shopping));refresh()};
  window.renderShop=function(){if(window.normalizeShopping)normalizeShopping();if(!shopping.length){shopList.innerHTML='<p class="muted">Einkaufsliste ist leer.</p>';return}shopList.innerHTML=shopping.map((s,i)=>`<div class="shop"><b>${s.n}</b>${s.q?' · '+s.q:''}${s.planGenerated?' <span class="pill">Wochenplan</span>':''}<div><button onclick="purchaseToStock(${i})" ${s.q?'':'disabled'}>Gekauft → Vorrat</button> <button class="secondary" onclick="shopping.splice(${i},1);saveShop()">Entfernen</button></div></div>`).join('')};
  function profileExtended(){const p=profile();if(!p.goal)p.goal='Vorrat zuerst';if(!p.maxMinutes)p.maxMinutes=60;return p}
  function injectProfileControls(){const card=document.querySelector('#profile .card');if(!card||document.getElementById('goal'))return;const btn=card.querySelector('button');const box=document.createElement('div');box.innerHTML=`<div class="grid2"><select id="goal"><option>Vorrat zuerst</option><option>Schnell</option><option>Proteinreich</option><option>Ballaststoffreich</option><option>Kalorienärmer</option></select><input id="maxMinutes" type="number" min="5" max="180" step="5" placeholder="Max. Kochzeit in Minuten"></div>`;card.insertBefore(box,btn);const p=profileExtended();goal.value=p.goal;maxMinutes.value=p.maxMinutes}
  window.saveProfile=function(){const old=profileExtended();localStorage.setItem('reserveProfile',JSON.stringify({people:Math.max(1,+people.value||1),diet:diet.value,avoid:avoid.value,dislikes:dislikes.value,goal:document.getElementById('goal')?.value||old.goal,maxMinutes:Math.max(5,+document.getElementById('maxMinutes')?.value||60)}));saved.textContent='Gespeichert.';refresh()};
  function expiryUrgency(r){let best=Number.MAX_SAFE_INTEGER;adaptRecipe(r).ingredients.forEach(i=>batches(i.name).forEach(b=>best=Math.min(best,parseDate(b.s.e))));return best}
  function preferenceScore(r){const p=profileExtended(),mins=(r.prepMinutes||0)+(r.cookMinutes||0);if(mins>p.maxMinutes)return 1e9;let score=0;if(p.goal==='Schnell')score+=mins;if(p.goal==='Proteinreich')score-=((r.nutrition||{}).protein||0)*2;if(p.goal==='Ballaststoffreich')score-=((r.nutrition||{}).fiber||0)*3;if(p.goal==='Kalorienärmer')score+=((r.nutrition||{}).kcal||0)/20;if(p.goal==='Vorrat zuerst'){const ex=expiryUrgency(r);score+=(ex===Number.MAX_SAFE_INTEGER?1e6:(ex-Date.now())/86400000)}return score}
  window.renderSmart=function(){let m=currentMeal(),pool=recipes.filter(r=>allowed(r)&&(r.mealTimes||[]).includes(m)&&preferenceScore(r)<1e9),ready=pool.filter(canCook).sort((a,b)=>preferenceScore(a)-preferenceScore(b)),near=pool.filter(r=>!canCook(r)).sort((a,b)=>(missingScore(a)+preferenceScore(a)/1000)-(missingScore(b)+preferenceScore(b)/1000)),list=(ready.length?ready:near).slice(0,4);timeLabel.textContent='Aktuell: '+m+' · '+profileExtended().goal;smartNow.innerHTML=list.length?`<div class="recipe-card-grid">${list.map(recipeCard).join('')}</div>`:'<p class="muted">Keine passenden Rezepte im gewählten Zeitlimit.</p>'};

  function virtualStock(){const ledger={};stock.forEach(s=>{const p=parseAmount(s.q);if(!p)return;const key=N(s.n)+'|'+p.u;if(!ledger[key])ledger[key]={name:s.n,u:p.u,v:0};ledger[key].v+=p.v});return ledger}
  function virtualEntry(ledger,name,unit){unit=(unit||'').toLowerCase()==='stück'?'stück':unit;const key=Object.keys(ledger).find(k=>{const e=ledger[k];return e.u===unit&&matchName(e.name,name)});return key?ledger[key]:null}
  function planCost(r,ledger){const a=adaptRecipe(r);let missingUnits=0,missingKinds=0,covered=0,total=0;a.ingredients.forEach(i=>{const req=i.amount*persons(),e=virtualEntry(ledger,i.name,unitOf(i)),have=e?Math.min(req,e.v):0;covered+=have/(req||1);total++;if(have<req){missingKinds++;missingUnits+=(req-have)/(req||1)}});return{score:missingUnits+missingKinds*.35-covered/Math.max(1,total)*.2,missingKinds}}
  function reserveVirtual(r,ledger,gaps){adaptRecipe(r).ingredients.forEach(i=>{const req=i.amount*persons(),u=unitOf(i),e=virtualEntry(ledger,i.name,u),take=e?Math.min(e.v,req):0;if(e)e.v-=take;const miss=req-take;if(miss>0){const key=N(i.name)+'|'+u;if(!gaps[key])gaps[key]={n:i.name,u,q:0};gaps[key].q+=miss}}})}
  function buildShoppingPlan(){let ledger=virtualStock(),eligible=recipes.filter(r=>allowed(r)&&preferenceScore(r)<1e9),plan=[],used=new Set(),gaps={};for(let day=1;day<=7;day++){let candidates=eligible.slice().sort((a,b)=>{const ca=planCost(a,ledger),cb=planCost(b,ledger);return ca.score-cb.score+(used.has(a.id)?0.18:0)-(used.has(b.id)?0.18:0)+((a.prepMinutes||0)+(a.cookMinutes||0)-(b.prepMinutes||0)-(b.cookMinutes||0))/1000});let pick=candidates[0];if(!pick){plan.push(null);continue}reserveVirtual(pick,ledger,gaps);used.add(pick.id);plan.push(pick)}return{plan,gaps}}
  window.addPlanShopping=function(){const x=buildShoppingPlan();shopping=shopping.filter(s=>!s.planGenerated);Object.values(x.gaps).forEach(g=>shopping.push({n:g.n,q:fmt(g.q,g.u),planGenerated:true}));localStorage.setItem('reserveShopping',JSON.stringify(shopping));renderShop();renderPlan()};
  window.renderPlan=function(){const x=buildShoppingPlan(),ready=x.plan.filter(r=>r&&!missing(r).length).length,gaps=Object.values(x.gaps);mealPlan.innerHTML=`<div class="plan-summary"><b>7-Tage-Plan erstellt · ${ready} Gericht${ready===1?'':'e'} aktuell sofort kochbar</b><div class="small muted">RESERVE nutzt deinen Vorrat zuerst und ergänzt nur die fehlenden Mengen für die Woche.</div></div>${x.plan.map((r,i)=>r?`<div class="meal"><b>Tag ${i+1}</b> · ${r.name}</div>`:`<div class="meal plan-gap"><b>Tag ${i+1}</b> · Kein passendes Rezept</div>`).join('')}${gaps.length?`<div class="plan-shopping"><h3>Für den Wochenplan fehlt</h3><div class="small muted">${gaps.map(g=>`${fmt(g.q,g.u)} ${g.n}`).join(' · ')}</div><button onclick="addPlanShopping()">Fehlende Mengen → Einkaufsliste</button></div>`:'<div class="available-card">✓ Der gesamte Wochenplan ist mit deinem Vorrat abgedeckt.</div>'}`};

  function progressKey(id){return 'reserveCookProgress:'+id}
  function cookProgress(id){try{return JSON.parse(localStorage.getItem(progressKey(id))||'[]')}catch{return[]}}
  window.toggleCookStep=function(id,i){let p=cookProgress(id);p[i]=!p[i];localStorage.setItem(progressKey(id),JSON.stringify(p));renderCook()};
  window.resetCookSteps=function(id){localStorage.removeItem(progressKey(id));renderCook()};
  function swapText(r){return (r.swaps||[]).map(x=>x.from+' → '+x.to).join(', ')}
  function ingredientCard(i){let u=unitOf(i),req=i.amount*persons(),have=available(i.name,u),miss=Math.max(0,req-have);return `<div class="ingredient ${miss?'is-missing':'in-stock'}"><div class="ingredient-visual" style="font-size:30px">${icon(i.name)}</div><div class="ingredient-name"><b>${i.name}</b></div><div class="ingredient-total">${fmt(req,i.unit)} <span class="small muted">gesamt</span></div><div class="perperson">${fmt(i.amount,i.unit)} / Person</div><div class="ingredient-state ${miss?'bad':'good'} pill">${miss?'Fehlt: '+fmt(miss,i.unit):'✓ vorhanden'}</div></div>`}
  function textList(title,items){return Array.isArray(items)&&items.length?`<section class="recipe-detail"><h3>${title}</h3><ul>${items.map(x=>`<li>${x}</li>`).join('')}</ul></section>`:''}
  function textDetail(title,text,cls=''){return text?`<section class="recipe-detail ${cls}"><h3>${title}</h3><p>${text}</p></section>`:''}
  window.renderCook=function(){let b=recipes.find(r=>r.id===cookRecipe.value);if(!b){cookView.innerHTML='';return}let r=adaptRecipe(b),d=missing(b),p=cookProgress(r.id),done=r.steps.filter((_,i)=>p[i]).length,swap=swapText(r),n=r.nutrition||{},allergens=(r.allergens||[]).join(', ');cookView.innerHTML=`<div class="cook-title"><div class="dish-symbol" aria-hidden="true" style="font-size:44px">${r.dish||'🍽️'}</div><h2>${r.name}</h2>${r.description?`<p class="recipe-description">${r.description}</p>`:''}<div class="recipe-meta"><span>${r.cuisine||''}</span><span>${r.difficulty||''}</span><span>${r.prepMinutes||0} Min. Vorbereitung</span><span>${r.cookMinutes||0} Min. Kochen</span></div></div><div class="portion"><b>${persons()} ${persons()===1?'Person':'Personen'} · ${done}/${r.steps.length} Schritte erledigt</b><div class="perperson">Alle Nährwerte und Einzelmengen sind pro Person angegeben; Gesamtmengen werden für deinen Haushalt berechnet.</div></div>${swap?`<div class="swap-note"><b>Automatisch angepasst:</b> ${swap}</div>`:''}${d.length?`<div class="missing-card"><div><strong>${missingSentence(d)}</strong><div class="small">Fehlende Mengen können direkt übernommen werden.</div></div><button onclick="addMissing('${r.id}')">+ Zur Einkaufsliste</button></div>`:'<div class="available-card">✓ Alle Zutaten sind im Vorrat.</div>'}<h3>Nährwerte pro Person</h3><div class="recipe-meta" style="margin:12px 0"><span>${Math.round(n.kcal||0)} kcal</span><span>${Math.round(n.protein||0)} g Protein</span><span>${Math.round(n.carbs||0)} g Kohlenhydrate</span><span>${Math.round(n.fat||0)} g Fett</span><span>${Math.round(n.fiber||0)} g Ballaststoffe</span></div>${allergens?`<div class="swap-note"><b>Allergene:</b> ${allergens}</div>`:''}${textList('Benötigte Geräte',r.equipment)}${textList('Vorbereitung',r.prepNotes)}<h3>Zutaten</h3><div class="ingredient-grid">${r.ingredients.map(ingredientCard).join('')}</div><h3>Zubereitung</h3>${r.steps.map((s,i)=>`<div class="step"><div class="stepno">${p[i]?'✓':i+1}</div><div style="flex:1;${p[i]?'opacity:.55;text-decoration:line-through':''}">${s}<br><button class="secondary" onclick="toggleCookStep('${r.id}',${i})">${p[i]?'Rückgängig':'Schritt erledigt'}</button></div></div>`).join('')}${textDetail('Woran erkenne ich, dass es fertig ist?',r.doneness,'doneness-detail')}${textList('Ersatzmöglichkeiten',r.substitutions)}${textDetail('Reste & Aufbewahrung',r.leftovers)}${textDetail('Lebensmittelsicherheit',r.safety,'safety-detail')}<button class="secondary" onclick="resetCookSteps('${r.id}')">Fortschritt zurücksetzen</button><button class="finish-cook" onclick="finishCook('${r.id}')" ${d.length||done<r.steps.length?'disabled':''}>✓ Gericht gekocht · Vorrat aktualisieren</button>`};
  const oldRefresh=window.refresh;window.refresh=function(){oldRefresh();injectProfileControls();renderShop();renderStock();renderPlan()};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',injectProfileControls);else injectProfileControls();
})();
