/* RESERVE shopping scan v1 — barcode-first add flow with quantity-aware confirmation and manual fallback. */
(function(){
  let stream=null,timer=null,zxingControls=null;
  const ZXING_URL='https://unpkg.com/@zxing/browser@0.2.1/umd/zxing-browser.min.js';
  const $=id=>document.getElementById(id);
  function stop(){if(timer)clearTimeout(timer);timer=null;if(zxingControls){try{zxingControls.stop()}catch{}zxingControls=null}if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}const v=$('shoppingScanVideo');if(v){try{v.pause()}catch{}v.srcObject=null}}
  function close(){stop();$('shoppingScanDialog')?.remove()}
  function manual(){close();$('shopInput')?.focus()}
  function displayQty(q){q=String(q||'').trim();const m=q.match(/^([0-9]+(?:[.,][0-9]+)?)\s*(g|kg|ml|l)$/i);if(!m)return q;const n=Number(m[1].replace(',','.')),u=m[2].toLowerCase();if(u==='g'&&n>=1000&&n%1000===0)return `${n/1000} kg`;if(u==='ml'&&n>=1000&&n%1000===0)return `${n/1000} l`;return `${String(n).replace('.',',')} ${u}`}
  function toast(text){document.getElementById('shoppingScanToast')?.remove();const e=document.createElement('div');e.id='shoppingScanToast';e.setAttribute('role','status');e.style.cssText='position:fixed;left:50%;bottom:24px;transform:translateX(-50%);z-index:10001;max-width:min(92vw,520px);padding:12px 16px;border-radius:12px;background:#173d2b;color:#fff;font-weight:700;box-shadow:0 8px 28px #0003;text-align:center';e.textContent=text;document.body.appendChild(e);setTimeout(()=>e.remove(),3200)}
  function add(name,code,qty){if(!name)return;qty=String(qty||'').trim();const item={n:name,q:qty||'1 stück',barcode:String(code||''),shoppingReasons:['Barcode-Scan']};if(window.RESERVE_SHOPPING?.upsert)RESERVE_SHOPPING.upsert(item);else{shopping.push(item);localStorage.setItem('reserveShopping',JSON.stringify(shopping));if(typeof renderShop==='function')renderShop()}close();toast(`✓ ${qty?displayQty(qty)+' ':''}${name} zur Einkaufsliste hinzugefügt`)}
  async function lookup(code){code=String(code||'').replace(/\D/g,'');if(!code)return;const remembered=window.RESERVE_BARCODE?.remembered?.(code);if(remembered?.name){add(remembered.name,code,remembered.qty);return}setStatus('Produkt wird gesucht…');try{const fields='product_name,product_name_de,quantity,product_quantity,product_quantity_unit';const r=await fetch('https://world.openfoodfacts.org/api/v2/product/'+encodeURIComponent(code)+'.json?fields='+fields,{headers:{Accept:'application/json'}});const d=await r.json(),p=d?.product||{},name=(p.product_name_de||p.product_name||'').trim(),qty=window.RESERVE_BARCODE?.quantityFromProduct?.(p)||'';if(name)add(name,code,qty);else{stop();setStatus('Produkt nicht gefunden. Bitte manuell eingeben.',true);$('shoppingScanManual').style.display='inline-block'}}catch{stop();setStatus('Produkt konnte nicht geladen werden. Bitte manuell eingeben.',true);$('shoppingScanManual').style.display='inline-block'}}
  function scanned(code){stop();lookup(code)}
  function setStatus(t,bad=false){const e=$('shoppingScanStatus');if(e){e.textContent=t;e.className='small '+(bad?'bad':'muted')}}
  function loadZXing(){if(window.ZXingBrowser)return Promise.resolve(window.ZXingBrowser);return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=ZXING_URL;s.async=true;s.onload=()=>window.ZXingBrowser?resolve(window.ZXingBrowser):reject();s.onerror=reject;document.head.appendChild(s)})}
  async function camera(){if(!navigator.mediaDevices?.getUserMedia){setStatus('Kamera nicht verfügbar. Bitte manuell eingeben.',true);$('shoppingScanManual').style.display='inline-block';return}try{const v=$('shoppingScanVideo');v.style.display='block';if('BarcodeDetector'in window){const formats=await BarcodeDetector.getSupportedFormats(),wanted=['ean_13','ean_8','upc_a','upc_e'].filter(x=>formats.includes(x));const detector=new BarcodeDetector({formats:wanted.length?wanted:formats});stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}}});v.srcObject=stream;await v.play();setStatus('Barcode vor die Kamera halten.');const scan=async()=>{if(!stream)return;try{const codes=await detector.detect(v);if(codes.length)return scanned(codes[0].rawValue)}catch{}timer=setTimeout(scan,300)};scan()}else{const ZX=await loadZXing(),reader=new ZX.BrowserMultiFormatOneDReader();setStatus('Barcode vor die Kamera halten.');zxingControls=await reader.decodeFromConstraints({audio:false,video:{facingMode:{ideal:'environment'}}},v,result=>{if(result)scanned(result.getText?.()||result.text||'')})}}catch{stop();setStatus('Scanner konnte nicht gestartet werden. Bitte Kameraberechtigung prüfen oder manuell eingeben.',true);$('shoppingScanManual').style.display='inline-block'}}
  function open(){close();const d=document.createElement('div');d.id='shoppingScanDialog';d.style.cssText='position:fixed;inset:0;z-index:10000;background:#0008;display:grid;place-items:center;padding:18px';d.innerHTML='<div class="card" style="width:min(520px,100%);max-height:90vh;overflow:auto"><h2>Lebensmittel hinzufügen</h2><p class="muted">Barcode scannen oder das Lebensmittel manuell eingeben.</p><video id="shoppingScanVideo" playsinline muted style="display:none;width:100%;max-height:330px;object-fit:cover;border-radius:14px"></video><p id="shoppingScanStatus" class="small muted">Scanner wird gestartet…</p><div style="display:flex;gap:8px;flex-wrap:wrap"><button id="shoppingScanManual" class="secondary">Manuell eingeben</button><button id="shoppingScanClose" class="secondary">Abbrechen</button></div></div>';document.body.appendChild(d);$('shoppingScanManual').onclick=manual;$('shoppingScanClose').onclick=close;camera()}
  function install(){const input=$('shopInput');if(!input)return;const btn=input.parentElement?.querySelector('button');if(!btn||btn.dataset.shoppingScanV1)return;btn.dataset.shoppingScanV1='1';btn.removeAttribute('onclick');btn.onclick=()=>{if(input.value.trim()){if(typeof addShop==='function')addShop();return}open()};btn.textContent='Hinzufügen / Scannen';}
  window.RESERVE_SHOPPING_SCAN={version:'1.1',open,close,lookup};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();