/* RESERVE visual flow — useful photos and actions, with learning kept behind the scenes. */
(function(){'use strict';if(window.RESERVE_VISUAL_FLOW)return;
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function product(row,index,label,bad=false){return `<button type="button" class="reserve-photo-item" data-index="${index}" aria-label="${esc(row.n)}, ${esc(label)}"><span class="cab-icon">${window.RESERVE_PRODUCT_ICONS?.iconFor?.(row)||'📦'}</span><span class="reserve-photo-copy"><strong>${esc(row.n)}</strong><span class="reserve-short-status ${bad?'reserve-overdue':''}">${esc(label)}</span></span></button>`}
function recipe(row){const path=row.image||'assets/recipes/'+row.id+'.png',url=/^(?:https:\/\/|assets\/)/i.test(path)?path:'';return `<button type="button" class="reserve-photo-recipe" data-recipe-id="${esc(row.id)}"><span class="reserve-dish-image">${url?`<img src="${esc(url)}" alt="" loading="lazy" decoding="async">`:''}<span class="reserve-dish-fallback" ${url?'hidden':''}>${esc(row.dish||'🍽️')}</span></span><strong>${esc(row.name)}</strong>${row.imageCredit?`<span class="reserve-photo-credit">Foto: ${esc(row.imageCredit.author)} · ${esc(row.imageCredit.license)}</span>`:''}</button>`}
function productCoverage(row){$('reserveProductCoverage')?.remove();const q=window.RESERVE_CABINET?.parseQty?.(row.q),l=q&&window.RESERVE_PANTRY_INTELLIGENCE?.quantityForecast?.(7,{includePlan:false})?.find(x=>x.name===row.n&&x.unit===q.u);if(!l?.learned||!['medium','high'].includes(l.learned.confidence)||!Number.isFinite(l.normalCoverageDays))return;const p=document.createElement('p');p.id='reserveProductCoverage';p.className='reserve-short-status';p.textContent='Reicht voraussichtlich ca. '+Math.max(0,Math.round(l.normalCoverageDays))+' Tage';$('cabinetProduct')?.querySelector('.cab-product-total')?.after(p)}
let captureOpen=false,captureScroll=0;
function capturePage(){let page=$('reserveCapture');if(!page){page=document.createElement('section');page.id='reserveCapture';page.className='panel';page.tabIndex=-1;page.innerHTML='<div class="card reserve-capture-head"><button type="button" id="reserveCaptureBack" class="secondary">← Zurück zum Vorrat</button><h2>Produkt erfassen</h2></div>';document.querySelector('main').appendChild(page);$('reserveCaptureBack').onclick=()=>{if(history.state?.reserveCapture)history.back();else{history.replaceState(null,'',location.pathname+location.search);routeCapture()}}}const barcode=$('barcodeCard'),manual=$('food')?.closest('.card'),receipt=$('receiptCard');for(const card of [barcode,manual,receipt])if(card&&card.parentElement!==page)page.appendChild(card);if(barcode&&manual&&barcode.nextElementSibling!==manual)barcode.after(manual);if($('scanAdd'))$('scanAdd').textContent='Zum Vorrat hinzufügen';return page}
function showCapture(){capturePage();captureOpen=true;document.querySelectorAll('.panel').forEach(p=>p.classList.toggle('active',p.id==='reserveCapture'));window.scrollTo(0,0);$('reserveCaptureBack')?.focus({preventScroll:true})}
function openCapture(){if(!captureOpen)captureScroll=window.scrollY;if(location.hash!=='#reserve-capture')history.pushState({reserveCapture:true},'','#reserve-capture');showCapture()}
function routeCapture(){if(location.hash==='#reserve-capture')showCapture();else if(captureOpen){captureOpen=false;$('reserveCapture')?.classList.remove('active');if(!location.hash.startsWith('#reserve-product=')){document.querySelectorAll('.panel').forEach(p=>p.classList.toggle('active',p.id==='stock'));requestAnimationFrame(()=>window.scrollTo(0,captureScroll))}}}
function arrange(){capturePage();const stock=$('stock'),cabinet=$('reserveCabinet')?.closest('.cabinet-card'),expiry=$('expiryIntelligence'),barcode=$('barcodeCard');if(!stock||!cabinet)return;if(stock.firstElementChild!==cabinet)stock.prepend(cabinet);if(expiry&&cabinet.nextElementSibling!==expiry)cabinet.after(expiry);['stockCoverage','reservePredictiveStock','pantryIntelligence','reserveToday'].forEach(id=>$(id)?.remove());const info=$('qualityInfo')?.closest('.card');if(info)info.hidden=true;const metric=$('qualityScore')?.closest('.metric');if(metric)metric.hidden=true;if(!cabinet.querySelector('#reserveQuickAdd')){const b=document.createElement('button');b.id='reserveQuickAdd';b.type='button';b.textContent='Produkt hinzufügen';b.className='secondary';b.onclick=openCapture;cabinet.querySelector('.cab-head')?.appendChild(b)}}
function boot(){const style=document.createElement('style');style.textContent=`
[hidden]{display:none!important}#reserveCapture{max-width:760px;margin:auto}#reserveCapture .reserve-capture-head{position:sticky;top:0;z-index:5}#reserveCapture .reserve-capture-head h2{margin:10px 0 0}.cab-head{flex-wrap:wrap}.cab-head #reserveQuickAdd{margin:0}.reserve-action-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.reserve-photo-item{display:flex;gap:10px;align-items:center;background:#fff!important;color:#20342a!important;border:1px solid #dce3d8;padding:10px!important;border-radius:14px!important;text-align:left;box-shadow:none!important;margin:0;min-width:0}.reserve-photo-item .cab-icon{display:flex;justify-content:center;align-items:center;background:#fff;width:64px;height:72px;flex:none;overflow:hidden;font-size:32px}.reserve-photo-item .cab-icon img{width:100%;height:100%;object-fit:contain}.reserve-photo-copy{display:flex;flex-direction:column;gap:6px;min-width:0}.reserve-photo-copy strong{font-size:14px;line-height:1.3;overflow-wrap:anywhere;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}.reserve-short-status{font-size:14px;font-weight:500;color:#49654f}.reserve-overdue{color:#984137}.reserve-photo-recipe{background:#fff!important;color:#20342a!important;border:1px solid #dce3d8;border-radius:14px!important;overflow:hidden;text-align:left;padding:0!important;margin:0;box-shadow:none!important;min-width:0}.reserve-photo-recipe strong{display:block;padding:10px;font-size:14px;line-height:1.35}.reserve-photo-credit{display:block;padding:0 10px 10px;font-size:11px;font-weight:400;line-height:1.4;color:#526356}.reserve-dish-image{display:grid;place-items:center;height:130px;background:#edf3ea}.reserve-dish-image img{width:100%;height:100%;object-fit:cover}.reserve-dish-fallback{font-size:42px}.recipe-visual{display:grid!important;place-items:center;height:160px;background:#edf3ea;font-size:44px}.recipe-visual img{width:100%;height:100%;object-fit:cover}#expiryIntelligence{border-left:1px solid var(--line)!important}#expiryIntelligence h3{margin:14px 0 10px}#expiryIntelligence h3:first-child{margin-top:0}@media(max-width:520px){.reserve-action-grid{grid-template-columns:1fr}.reserve-photo-item .cab-icon{width:72px;height:76px}.reserve-photo-copy strong{font-size:16px}}@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important}}
`;document.head.appendChild(style);document.addEventListener('click',e=>{const tile=e.target.closest('.reserve-photo-item');if(tile){const row=window.RESERVE_CABINET?.getStock?.()[Number(tile.dataset.index)];if(row){const key=row.barcode?'barcode:'+row.barcode:'name:'+String(row.n||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/g,'');window.RESERVE_CABINET.openProduct(key)}}const r=e.target.closest('[data-recipe-id]');if(r&&typeof startCook==='function')startCook(r.dataset.recipeId)});document.addEventListener('error',e=>{const img=e.target;if(img.tagName==='IMG'&&img.closest('.reserve-dish-image')){img.hidden=true;const f=img.parentElement.querySelector('.reserve-dish-fallback');if(f)f.hidden=false}},true);window.addEventListener('popstate',routeCapture);window.addEventListener('hashchange',routeCapture);document.querySelector('header nav')?.addEventListener('click',()=>{if(captureOpen){captureOpen=false;history.replaceState(null,'',location.pathname+location.search)}});arrange();if(location.hash==='#reserve-capture'||new URLSearchParams(location.search).has('reserveScanned')||new URLSearchParams(location.search).get('scannerReturn')==='1')openCapture();window.RESERVE_EXPIRY_UI?.render?.();window.addEventListener('reserve:cabinet-rendered',arrange);window.addEventListener('reserve:stock-changed',()=>requestAnimationFrame(()=>{window.RESERVE_EXPIRY_UI?.render?.();arrange()}));window.addEventListener('reserve:ui-refreshed',()=>requestAnimationFrame(arrange));}
window.RESERVE_VISUAL_FLOW={product,recipe,productCoverage,arrange,openCapture};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
