/* RESERVE Weekly Plan v2.1 — 21 meals, calorie targets and consolidated shopping gaps. */
(function(){
 const TIMES=['Frühstück','Mittagessen','Abendessen'],DAYS=['Montag','Dienstag','Mittwoch','Donnerstag','Freitag','Samstag','Sonntag'],SHARE={Frühstück:.25,Mittagessen:.4,Abendessen:.35};
 const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/g,'');
 const unit=u=>{u=String(u||'stück').toLowerCase();return u==='stuck'||u==='stk'?'stück':u};
 function rows(){try{return Array.isArray(recipes)?recipes:[]}catch{return Array.isArray(window.recipes)?window.recipes:[]}}
 function ok(r){try{return typeof allowed==='function'?allowed(r):true}catch{return true}}
 function people(){try{return Math.max(1,persons())}catch{return 1}}
 function target(){return Math.max(800,+localStorage.getItem('reserveDailyKcalTarget')||2000)}
 function kcal(r){return +(r?.nutrition?.kcal||0)||0}
 function mealFits(r,t){const a=Array.isArray(r.mealTimes)?r.mealTimes:[];return a.includes(t)||(t!=='Frühstück'&&a.includes('Hauptmahlzeit'))}
 function stockMap(){const m={};try{stock.forEach(s=>{const p=parseAmount(s.q);if(!p)return;const k=norm(s.n)+'|'+unit(p.u);(m[k]??={name:s.n,unit:unit(p.u),v:0}).v+=p.v})}catch{}return m}
 function adapt(r){try{return typeof adaptRecipe==='function'?adaptRecipe(r):r}catch{return r}}
 function reserveWithGaps(r,m,gaps){for(const i of (adapt(r).ingredients||[])){const u=unit(i.unit),need=(+i.amount||0)*people(),keys=Object.keys(m),key=keys.find(k=>{const [n,ku]=k.split('|');return ku===u&&(n.includes(norm(i.name))||norm(i.name).includes(n))}),have=key?m[key].v:0,use=Math.min(have,need);if(key)m[key].v-=use;const miss=need-use;if(miss>0){const gk=norm(i.name)+'|'+u;(gaps[gk]??={name:i.name,unit:u,amount:0}).amount+=miss}}}}
 function build(){const m=stockMap(),gaps={},pool=rows().filter(ok),used=new Map(),days=[];for(let d=0;d<7;d++){const meals=[];for(const time of TIMES){const goal=target()*SHARE[time],candidates=pool.filter(r=>mealFits(r,time));candidates.sort((a,b)=>(used.get(a.id)||0)-(used.get(b.id)||0)+Math.abs(kcal(a)-goal)/10000-Math.abs(kcal(b)-goal)/10000);const pick=candidates[0]||null;if(pick){reserveWithGaps(pick,m,gaps);used.set(pick.id,(used.get(pick.id)||0)+1)}meals.push({time,recipe:pick,kcal:pick?kcal(pick):0,target:goal})}const dayKcal=meals.reduce((s,x)=>s+x.kcal,0);days.push({day:DAYS[d],meals,kcal:dayKcal,target:target(),delta:dayKcal-target()})}return{version:'2.1',days,slots:days.flatMap(d=>d.meals),filled:days.flatMap(d=>d.meals).filter(x=>x.recipe).length,shopping:Object.values(gaps).filter(x=>x.amount>0),dailyTarget:target()}}
 function amount(v,u){try{return fmt(v,u)}catch{return `${Math.round(v*10)/10} ${u}`}}
 function addShopping(){const x=build(),add=x.shopping;try{for(const g of add){let e=shopping.find(s=>norm(s.n)===norm(g.name));if(e){const p=parseAmount(e.q);if(p&&unit(p.u)===g.unit)e.q=amount(p.v+g.amount,g.unit);else e.q=amount(g.amount,g.unit)}else shopping.push({n:g.name,q:amount(g.amount,g.unit),weeklyPlan:true})}saveShop();return add.length}catch{return 0}}
 function ensureProfile(){const sec=document.getElementById('profile'),card=sec?.querySelector('.card');if(!card||document.getElementById('dailyKcalTarget'))return;const box=document.createElement('div');box.innerHTML='<label class="small muted" for="dailyKcalTarget">Tägliches Kalorienziel pro Person</label><input id="dailyKcalTarget" type="number" min="800" max="6000" step="50">';const btn=card.querySelector('button[onclick="saveProfile()"]');card.insertBefore(box,btn);dailyKcalTarget.value=target();btn?.addEventListener('click',()=>{localStorage.setItem('reserveDailyKcalTarget',Math.max(800,+dailyKcalTarget.value||2000));render()})}
 function render(){ensureProfile();const el=document.getElementById('mealPlan');if(!el)return null;const x=build();const gaps=x.shopping.length;el.innerHTML=`<div class="plan-summary"><b>${x.filled}/21 Mahlzeiten geplant · Ziel ${x.dailyTarget} kcal/Tag</b><div class="small muted">RESERVE plant Frühstück, Mittagessen und Abendessen und berechnet fehlende Wochenzutaten automatisch.</div>${gaps?`<button id="weeklyShop">${gaps} fehlende Zutaten zur Einkaufsliste</button>`:'<div class="small good">✓ Alle geplanten Zutaten sind im Vorrat.</div>'}</div>`+x.days.map(d=>`<div class="meal"><h3>${d.day} · ${Math.round(d.kcal)} / ${d.target} kcal</h3>${d.meals.map(m=>m.recipe?`<div><b>${m.time}</b> · ${m.recipe.name}${m.kcal?` <span class="small muted">${Math.round(m.kcal)} kcal</span>`:''}</div>`:`<div class="plan-gap"><b>${m.time}</b> · Kein passendes Rezept verfügbar</div>`).join('')}</div>`).join('');const b=document.getElementById('weeklyShop');if(b)b.onclick=()=>{const n=addShopping();b.textContent=`${n} Position${n===1?'':'en'} übernommen`;b.disabled=true};return x}
 window.RESERVE_WEEKLY_PLAN={version:'2.1',times:TIMES,days:DAYS,build,render,addShopping,target};window.renderPlan=render;setTimeout(render,0);
})();
